### ISSUE TITLE
Allow T1w only for analysis

### ISSUE THREAD

**Issue by Clancy-wu** [PennLINC/xcp_d#1000]
I'm tring to use xcp_d, but it reports error continuely for my fmriprep data which contains t1w structural image only.
version:  V0.6
command: demo simple command
process detail:
    collected data:
    bold: /fmriprep/sub001/func/xx.nii.gz
    t1w: /fmriprep/sub001/anat/xx_T1w.nii.gz
    t2w: null
report: FileNotFoundError: No T1w or T2w files found.
I know that xcp_d use a minimal processes on structural image with T1w and T2w image. But I wonder could you please add a function to exlusive T2w? 
Not all the data have both T1w and T2w and the only T1w is allowed for fmriprep process. I guess it would be better for researcher to choose including T1w only.

**Comment by tsalo** [comment]
XCP-D should be able to handle T1w-only data without issue. All of our test datasets only have preprocessed T1w images.

**Comment by Clancy-wu** [comment]
Well, that's great, but I don't know why I cannot run xcp_d well, could you please help me to check?
*system:*
ubuntu 20.04 LST
fmriprep version 21.04
xcp_d version v0.6.0
 
*running command: *
>    docker run --rm -it \
>    -v /home/clancy/data/xcp_d/fmriprep:/fmriprep:ro \
>    -v /home/clancy/data/xcp_d/work:/work:rw \
>    -v /home/clancy/data/xcp_d/output:/out:rw \
>    pennlinc/xcp_d:v0.6.0 \
>    /fmriprep /out participant \
>    --input-type fmriprep \
>    --smoothing 6 \
>    -p 36P \
>    --lower-bpf 0.008 \
>    --upper-bpf 0.08 \
>    -w work \
>    --cifti \
>    --resource-monitor

process details:
>  231121-19:49:48,722 nipype.workflow IMPORTANT:
>	 Running xcp_d version 0.6.0rc6:
>    * fMRI directory path: /fmriprep.
>    * Participant list: ['1001', '1003', '1009', '1013', '1015', '1016', '1017', '1019', '1021', '1022', '1023', '1024', '1026', '1027', '1028', '1029', '1032', '1036', '1037', '1038', '1039', '1040', '1043', '1046', '1047', '1049', '1050', '1052', '1053', '1054'].
> * Run identifier: 20231121-194948_f19994ee-725f-4f4a-b408-ca209614a868.
> 231121-19:49:48,854 nipype.utils IMPORTANT:
>	 Collected data:
> anat_brainmask: /fmriprep/sub-1001/anat/sub-1001_desc-brain_mask.nii.gz
> anat_dseg: /fmriprep/sub-1001/anat/sub-1001_dseg.nii.gz
> anat_to_template_xfm: /fmriprep/sub-1001/anat/sub-1001_from-T1w_to-MNI152NLin6Asym_mode-image_xfm.h5
> bold:
> - /fmriprep/sub-1001/func/sub-1001_task-rest_space-fsLR_den-91k_bold.dtseries.nii
> t1w: /fmriprep/sub-1001/anat/sub-1001_desc-preproc_T1w.nii.gz
> t2w: null
> template_to_anat_xfm: /fmriprep/sub-1001/anat/sub-1001_from-MNI152NLin6Asym_to-T1w_mode-image_xfm.h5
> 231121-19:49:48,924 nipype.utils IMPORTANT:
>	 Collected mesh files:
> lh_pial_surf: /fmriprep/sub-1001/anat/sub-1001_hemi-L_pial.surf.gii
> lh_wm_surf: /fmriprep/sub-1001/anat/sub-1001_hemi-L_smoothwm.surf.gii
> rh_pial_surf: /fmriprep/sub-1001/anat/sub-1001_hemi-R_pial.surf.gii
> rh_wm_surf: /fmriprep/sub-1001/anat/sub-1001_hemi-R_smoothwm.surf.gii
> 231121-19:49:48,971 nipype.utils IMPORTANT:
> 	 Collected morphometry files:
> cortical_thickness: null
> cortical_thickness_corr: null
> myelin: null
> myelin_smoothed: null
> sulcal_curv: null
> sulcal_depth: null
> Downloading https://templateflow.s3.amazonaws.com/tpl-MNI152NLin6Asym/tpl-MNI152NLin6Asym_res-01_T1w.nii.gz
> 100%|██████████████████████████████████████| 11.0M/11.0M [00:02<00:00, 5.08MB/s]
> 231121-19:49:52,182 nipype.utils IMPORTANT:
> 	 Collected run data for sub-1001_task-rest_space-fsLR_den-91k_bold.dtseries.nii:
> boldref: /fmriprep/sub-1001/func/sub-1001_task-rest_space-MNI152NLin6Asym_res-2_boldref.nii.gz
> confounds: /fmriprep/sub-1001/func/sub-1001_task-rest_desc-confounds_timeseries.tsv
> confounds_json: /fmriprep/sub-1001/func/sub-1001_task-rest_desc-confounds_timeseries.json
> nifti_file: /fmriprep/sub-1001/func/sub-1001_task-rest_space-MNI152NLin6Asym_res-2_desc-preproc_bold.nii.gz
> Downloading https://templateflow.s3.amazonaws.com/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_desc-> brain_mask.nii.gz
> 100%|██████████████████████████████████████| 29.6k/29.6k [00:00<00:00, 1.07MB/s]
> Analyzing data at the participant level
> Process Process-2:
> Traceback (most recent call last):
>   File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
>    self.run()
>  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
>    self._target(*self._args, **self._kwargs)
>  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/cli/run.py", line 977, in build_workflow
>    retval["workflow"] = init_xcpd_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflows/base.py", line 199, in init_xcpd_wf
    single_subj_wf = init_subject_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflows/base.py", line 370, in init_subject_wf
    layout, subj_data = collect_data(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/utils/bids.py", line 331, in collect_data
    raise FileNotFoundError("No T1w or T2w files found.")
>  FileNotFoundError: No T1w or T2w files found.

My data was processed by fmriprep with succesfully finished and was in fmriprep type orgnization. Process details showed bold file and t1w file.
Do you have any idea?

**Comment by Clancy-wu** [comment]
Oh, how stupid am I. I just forget "never work the data without check". I find that one subject was error with fmriprep process. 
I apologize for any trouble brough by my mistake and I will continue to pay attention to your work.
Your work is great and meaningful.
