### ISSUE TITLE
xcp_d: error: the following arguments are required: analysis_level

### ISSUE THREAD

**Issue by connectomeclara** [PennLINC/xcp_d#1015]
## Summary

I ran "xcp_d fmriprep_dir output_dir --cifti --despike  --head_radius 40 -w /wkdir --smoothing 6" and it gave me an error stating `xcp_d: error: the following arguments are required: analysis_level`

## Additional details

- xcp_d version: xcp_d v0.6.1.dev3+geeea98a
- Docker version: Docker version 24.0.6, build ed223bc

### What were you trying to do?
I was trying to run  `xcp_d fmriprep_dir output_dir --cifti --despike  --head_radius 40 -w /wkdir --smoothing 6`

### What did you expect to happen?
I expected the output to be:
```
usage: xcp_d [-h] [--version]
             [--participant_label PARTICIPANT_LABEL [PARTICIPANT_LABEL ...]]
             [-t TASK_ID] [--bids-filter-file FILE] [-m] [-s]
             [--nthreads NTHREADS] [--omp-nthreads OMP_NTHREADS]
             [--mem_gb MEM_GB] [--use-plugin USE_PLUGIN] [-v]
             [--input-type {fmriprep,dcan,hcp,nibabies}]
             [--smoothing SMOOTHING] [--despike]
             [-p {27P,36P,24P,acompcor,aroma,acompcor_gsr,aroma_gsr,custom,none}]
             [-c CUSTOM_CONFOUNDS] [--min_coverage MIN_COVERAGE]
             [--min_time MIN_TIME] [--dummy-scans {{auto,INT}}]
             [--random-seed _RANDOM_SEED] [--disable-bandpass-filter]
             [--lower-bpf LOWER_BPF] [--upper-bpf UPPER_BPF]
             [--bpf-order BPF_ORDER] [--motion-filter-type {lp,notch}]
             [--band-stop-min BPM] [--band-stop-max BPM]
             [--motion-filter-order MOTION_FILTER_ORDER] [-r HEAD_RADIUS]
             [-f FD_THRESH] [--exact-time EXACT_TIME [EXACT_TIME ...]]
             [-w WORK_DIR] [--clean-workdir] [--resource-monitor] [--notrack]
             [--fs-license-file FILE] [--warp-surfaces-native2std] [--dcan-qc]
             fmri_dir output_dir {participant}
```

### What actually happened?
![image](https://github.com/PennLINC/xcp_d/assets/153136333/68a81d8b-7df5-4331-8d5e-550a9789177d)
```
usage: xcp_d [-h] [--version] [--participant_label PARTICIPANT_LABEL [PARTICIPANT_LABEL ...]] [-t TASK_ID] [--bids-filter-file FILE] [-m] [-s]
             [--nthreads NTHREADS] [--omp-nthreads OMP_NTHREADS] [--mem_gb MEM_GB] [--use-plugin USE_PLUGIN] [-v]
             [--input-type {fmriprep,dcan,hcp,nibabies}] [--smoothing SMOOTHING] [--despike]
             [-p {27P,36P,24P,acompcor,aroma,acompcor_gsr,aroma_gsr,custom,none}] [-c CUSTOM_CONFOUNDS] [--min_coverage MIN_COVERAGE]
             [--min_time MIN_TIME] [--dummy-scans {{auto,INT}}] [--random-seed _RANDOM_SEED] [--disable-bandpass-filter] [--lower-bpf LOWER_BPF]
             [--upper-bpf UPPER_BPF] [--bpf-order BPF_ORDER] [--motion-filter-type {lp,notch}] [--band-stop-min BPM] [--band-stop-max BPM]
             [--motion-filter-order MOTION_FILTER_ORDER] [-r HEAD_RADIUS] [-f FD_THRESH] [--exact-time EXACT_TIME [EXACT_TIME ...]] [-w WORK_DIR]
             [--clean-workdir] [--resource-monitor] [--notrack] [--fs-license-file FILE] [--warp-surfaces-native2std] [--dcan-qc]
             fmri_dir output_dir {participant}
xcp_d: error: the following arguments are required: analysis_level
```

## Reproducing the bug
 First I installed xcp then `xcp_d fmriprep_dir output_dir --cifti --despike  --head_radius 40 -w /wkdir --smoothing 6`

**Comment by tsalo** [comment]
Based on your command, you didn't include the analysis level, which is a required parameter for all BIDS Apps.

Instead of

```bash
xcp_d fmriprep_dir output_dir --cifti --despike  --head_radius 40 -w /wkdir --smoothing 6
```

you should do

```bash
xcp_d fmriprep_dir output_dir participant --cifti --despike  --head_radius 40 -w /wkdir --smoothing 6
```

**Comment by connectomeclara** [comment]
[image: image.png]
Hello! When I run that command I got the following.

**Comment by connectomeclara** [comment]
Hello everyone! I tried a new command: `sudo docker run -it --rm -v /home/ra/xx-derivatives:/fmriprep:ro -v /tmp/wkdir:/work:rw -v /home/ra/test:/out:rw -v /home/freesurfer:/freesurfer:ro pennlinc/xcp_d:latest /fmriprep /out participant --participant-label 050 -w /work --despike --head_radius 40 --smoothing 6 -d 8 --cifti`

But I got: ```
usage: xcp_d [-h] [--version] [--participant_label PARTICIPANT_LABEL [PARTICIPANT_LABEL ...]] [-t TASK_ID] [--bids-filter-file FILE] [-m] [-s]
             [--nthreads NTHREADS] [--omp-nthreads OMP_NTHREADS] [--mem_gb MEM_GB] [--use-plugin USE_PLUGIN] [-v]
             [--input-type {fmriprep,dcan,hcp,nibabies}] [--smoothing SMOOTHING] [--despike]
             [-p {27P,36P,24P,acompcor,aroma,acompcor_gsr,aroma_gsr,custom,none}] [-c CUSTOM_CONFOUNDS] [--min_coverage MIN_COVERAGE]
             [--min_time MIN_TIME] [--dummy-scans {{auto,INT}}] [--random-seed _RANDOM_SEED] [--disable-bandpass-filter] [--lower-bpf LOWER_BPF]
             [--upper-bpf UPPER_BPF] [--bpf-order BPF_ORDER] [--motion-filter-type {lp,notch}] [--band-stop-min BPM] [--band-stop-max BPM]
             [--motion-filter-order MOTION_FILTER_ORDER] [-r HEAD_RADIUS] [-f FD_THRESH] [--exact-time EXACT_TIME [EXACT_TIME ...]] [-w WORK_DIR]
             [--clean-workdir] [--resource-monitor] [--notrack] [--fs-license-file FILE] [--warp-surfaces-native2std] [--dcan-qc]
             fmri_dir output_dir {participant}
xcp_d: error: unrecognized arguments: -d 8
```
