### ISSUE TITLE
Add more BIDS App parameters

### ISSUE THREAD

**Issue by tsalo** [PennLINC/xcp_d#1041]
## Summary

In working on #1040, I noticed that a bunch of command-line arguments in ASLPrep aren't in XCP-D. At least some of them seem like they could be useful in XCP-D.

- ~~`--stop-on-first-crash`: Whether the workflow should stop or continue after the first error. In config, but not CLI.~~ Implemented in #1044.
- `--boilerplate_only`: Only generate a boilerplate.
- `--sloppy`: Run in sloppy mode (meaning, suboptimal parameters that minimize run-time).
    - I'm not sure how applicable this is to XCP-D.
- `--debug`: Debug mode(s). In config, but not CLI.
- `--fs_subjects_dir`?
- `--md_only_boilerplate`: Do not convert boilerplate from MarkDown to LaTex and HTML. In config, but not CLI.
- `--low_mem`: Utilize uncompressed NIfTIs and other tricks to minimize memory allocation.
- `--write_graph`: Write out the computational graph corresponding to the planned preprocessing. In config, but not CLI.

**Comment by psychelzh** [comment]
Especially requires `--stop-on-first-crash`, now the pipeline won't stop after many crashes and requires a manual stop for my case.

**Comment by tsalo** [comment]
I think #1040 addressed this.
