### ISSUE TITLE
Allow the pipeline to keep minimal data

### ISSUE THREAD

**Issue by psychelzh** [PennLINC/xcp_d#1049]
## Summary

I have a pipeline with single subject completing many tasks in fMRI scanner, which turns out to be very storage consuming. Thus minimal data storage can be especially important.

## Additional details

For now, I found that both original and smoothed data are stored. How about only keeping the smoothed ones?

## Next steps

Maybe add some cli argument, e.g., `--minimal-storage`?

**Comment by tsalo** [comment]
I would recommend having a step that removes unwanted files after the workflow finishes. That's what we do in the PennLINC lab when we run tools like XCP-D.
