### ISSUE TITLE
Stop appending pipeline name to output directory

### ISSUE THREAD

**Issue by tsalo** [PennLINC/xcp_d#1050]
## Summary

Other BIDS Apps are moving away from hardcoded output folder names (e.g., fMRIPrep, ASLPrep), so it makes sense to do this for XCP-D, although it will be a breaking change.

## Additional details

It will bring XCP-D in line with other BIDS Apps and will also make it easier for users to run multiple versions of XCP-D without extra work, as they could customize the output folder.

**Comment by mattcieslak** [comment]
Check with hbcd to make sure they don't start missing outputs

**Comment by tsalo** [comment]
👍 from @madisoth and @tjhendrickson
