### ISSUE TITLE
Do not warn if `fd-thresh` and `min-time` are both set as 0

### ISSUE THREAD

**Issue by psychelzh** [PennLINC/xcp_d#1055]
## Summary

A little annoying warning appears.

## Additional details

- xcp_d version: latest unstable version
- Docker version: not related
- Singularity version: not related

### What were you trying to do?

If I want to turn off motion scrubbing by setting `fd-thresh` as `0`, `xcp_d` will always throw a warning as follows:

```
    Framewise displacement-based scrubbing is disabled. The following parameters will have no effect:
	--min-time
```

Even if I do not set `min-time` explicitly or set `min-time` as `0`.

### What did you expect to happen?

If I do not set `min-time` explicitly or set `min-time` as `0` (especially in this case), the warning should be dismissed.

**Comment by tsalo** [comment]
I'm happy to drop the warning when `min-time` is 0, but the default is 100 so I the warning still applies in that case.
