### ISSUE TITLE
Anat-to-template xfms not found for NiBabies T2w-only subjects

### ISSUE THREAD

**Issue by madisoth** [PennLINC/xcp_d#1057]
## Summary

NiBabies T2w-only (MCRIBS) subjects fail 
## Additional details

- xcp_d version: 0.6.1
- Docker version:
- Singularity version: 1.2.5-1.el7

### What were you trying to do?

Run a T2w-only infant subject processed with NiBabies 24.0.0a1 using `--surface-recon-method mcribs`, `--cifti-output 91k`, and `--output-spaces MNI152NLin6Asym:res-2`

### What actually happened?
xcp_d failed during initial collection of the subject's NiBabies derivatives:
```
240220-14:47:49,938 nipype.workflow IMPORTANT:
	 Running xcp_d version 0.6.1:
    * fMRI directory path: /input.
    * Participant list: ['XXXXXX'].
    * Run identifier: 20240220-144749_700f0aaa-1e9d-4c99-aac1-eecb6aec0136.


240220-14:47:50,116 nipype.workflow INFO:
	 Beginning the xcpd_wf workflow
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.10/site-packages/xcp_d/cli/run.py", line 1049, in build_workflow
    retval["workflow"] = init_xcpd_wf(
  File "/usr/local/miniconda/lib/python3.10/site-packages/xcp_d/workflows/base.py", line 202, in init_xcpd_wf
    single_subj_wf = init_subject_wf(
  File "/usr/local/miniconda/lib/python3.10/site-packages/xcp_d/workflows/base.py", line 377, in init_subject_wf
    layout, subj_data = collect_data(
  File "/usr/local/miniconda/lib/python3.10/site-packages/xcp_d/utils/bids.py", line 305, in collect_data
    raise FileNotFoundError(
FileNotFoundError: No BOLD NIfTI or transforms found to allowed space (MNI152NLin2009cAsym)
```

## Reproducing the bug

- xcp_d was run using args `--input-type nibabies --cifti --combineruns -r 45 -f 0.2 -w /work /input /output participant`

- some print statements I added to utils/bids.py immediately before the point of the error output the following:
```
volspace: MNI152NLin6Asym
allowed_spaces: ['MNI152NLin6Asym', 'MNIInfant', 'MNI152NLin2009cAsym']
transform_files: []
bold_data [<BIDSImageFile filename='/input/sub-204271/ses-V02/func/sub-204271_ses-V02_task-rest_dir-PA_run-1_space-MNI152NLin6Asym_res-2_desc-preproc_bold.nii.gz'>, <BIDSImageFile filename='/input/sub-204271/ses-V02/func/sub-204271_ses-V02_task-rest_dir-PA_run-2_space-MNI152NLin6Asym_res-2_desc-preproc_bold.nii.gz'>]
temp_xfm_query: {'datatype': 'anat', 'from': 'T1w', 'suffix': 'xfm', 'to': 'MNI152NLin6Asym'}

```

- In utils/bids.py, moving the check for whether the subject is T2w-only (https://github.com/PennLINC/xcp_d/blob/1d7bce24ae70f955d64641afbb75226267c3fd27/xcp_d/utils/bids.py#L327) to before the first instance of `queries["anat_to_template_xfm"]` / `queries["template_to_anat_xfm"]` appears to fix the issue for this subject

**Comment by tsalo** [comment]
Do your Nibabies derivatives include a T1w?

**Comment by tjhendrickson** [comment]
Hi @tsalo for this participant no T1w was collected, only a T2w.

**Comment by tsalo** [comment]
Ah, I see. My T2w-only test involves copying the T1w-related files as T2w versions, without deleting the originals, so the original transform was still being detected. I'm updating the test in #1060 and will include a fix there. Thanks!
