### ISSUE TITLE
Attachment of confound file to another bold image

### ISSUE THREAD

**Issue by tjhendrickson** [PennLINC/xcp_d#1062]
## Summary
NiBabies finished to completion, however, for whatever reason a confound timeseries TSV was not generated for one of the runs. When running XCP-D, it associated the confound timeseries TSV with an unassociated bold timeseries. The confound timeseries TSV and bold timeseries were of different length, which resulted in an array mismatch, and caused a failure.

## Additional details

- xcp_d version: 0.6.1
- Docker version:
- Singularity version: 0.6.1

## Reproducing the bug

Nibabies preproc files along with their volumes:
- sub-958739_ses-V02_task-rest_dir-PA_run-1_space-MNI152NLin6Asym_res-2_desc-preproc_bold.nii.gz -> 141
- sub-958739_ses-V02_task-rest_dir-PA_run-2_space-MNI152NLin6Asym_res-2_desc-preproc_bold.nii.gz -> 261
- sub-958739_ses-V02_task-rest_dir-PA_run-3_space-MNI152NLin6Asym_res-2_desc-preproc_bold.nii.gz -> 261

Confound files along with rows:
- sub-958739_ses-V02_task-rest_dir-PA_run-1_desc-confounds_timeseries.tsv -> 141
- missing confound for second run (?)
- sub-958739_ses-V02_task-rest_dir-PA_run-3_desc-confounds_timeseries.tsv -> 261

Critical snippet from standard out log showcasing association
```
240222-09:33:48,185 nipype.utils IMPORTANT:
	 Collected run data for sub-958739_ses-V02_task-rest_dir-PA_run-2_space-fsLR_den-91k_bold.dtseries.nii:
boldref: /input/sub-958739/ses-V02/func/sub-958739_ses-V02_task-rest_dir-PA_run-2_space-MNI152NLin6Asym_res-2_boldref.nii.gz
confounds: /input/sub-958739/ses-V02/func/sub-958739_ses-V02_task-rest_dir-PA_run-1_desc-confounds_timeseries.tsv
confounds_json: /input/sub-958739/ses-V02/func/sub-958739_ses-V02_task-rest_dir-PA_run-1_desc-confounds_timeseries.json
nifti_file: /input/sub-958739/ses-V02/func/sub-958739_ses-V02_task-rest_dir-PA_run-2_space-MNI152NLin6Asym_res-2_desc-preproc_bold.nii.gz
```

Additional here is the stacktrace error message:
```
++ Final vox neighbood: ellipsoid with Nneigh=27 and radii (1.900,1.900,1.900).
++ ReHo (Kendall's W) calculated.
++ Final vox neighbood: ellipsoid with Nneigh=27 and radii (1.900,1.900,1.900).
++ ReHo (Kendall's W) calculated.
xcp_d failed: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.10/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node regress_and_filter_bold.
Traceback:
	Traceback (most recent call last):
	  File "/usr/local/miniconda/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 397, in run
	    runtime = self._run_interface(runtime)
	  File "/usr/local/miniconda/lib/python3.10/site-packages/xcp_d/interfaces/nilearn.py", line 304, in _run_interface
	    ) = denoise_with_nilearn(
	  File "/usr/local/miniconda/lib/python3.10/site-packages/xcp_d/utils/utils.py", line 390, in denoise_with_nilearn
	    preprocessed_bold_censored = preprocessed_bold[sample_mask, :]
	  File "/usr/local/miniconda/lib/python3.10/site-packages/numpy/core/memmap.py", line 335, in __getitem__
	    res = super().__getitem__(index)
	IndexError: boolean index did not match indexed array along dimension 0; dimension is 261 but corresponding boolean dimension is 141
pandoc-citeproc: reference hcppipelines not found
```

**Comment by tsalo** [comment]
XCP-D relies on PyBIDS's get_nearest method to find the confounds file, but it's not being strict enough. This is definitely an edge case where the preprocessing derivatives aren't complete (i.e., it would be fine if run 2's confounds file was available), but it's also a bug that could go completely unnoticed if users don't review the logs in intense detail.

The same could apply to other associated files for the BOLD run.
