### ISSUE TITLE
Inconsistent slice cut coordinates in DCAN ES boldref and mean plots

### ISSUE THREAD

**Issue by madisoth** [PennLINC/xcp_d#1101]
## Summary

In the `--dcan-qc` executive summary, the slice cut coordinates for task mean and boldref plots are based center of mass, instead of center of FOV like in the DCAN pipelines' executive summary; seems to be because NiLearn's plot_anat uses center of mass versus DCAN pipeline using FSL `slicer -a` -- "output mid-sagittal, -coronal and -axial slices into one image"). Because of this, the boldref and mean plots for a single run sometimes show different slices. 

## Additional details

- xcp_d version: 0.6.1
- Docker version:
- Singularity version: apptainer 1.2.5-1.el7

**Comment by tsalo** [comment]
Do you still want a single orth set (1 axial, 1 sagittal, 1 coronal), or a full 1x9 slicer output?

**Comment by tsalo** [comment]
@madisoth just so you know, I ended up hardcoding in [0, 0, 0] in the Nilearn plotting function call. I think that makes figures look like how you want, but if you don't like the result I can look at the `slicer` approach.
