### ISSUE TITLE
KeyError "rmsd"

### ISSUE THREAD

**Issue by joebathelt** [PennLINC/xcp_d#1125]
## Additional details

- xcp_d version: latest (Created: 2024-03-22T19:59:37.757112854Z)
- Docker version: 26.0.0

### What were you trying to do?
I'm trying to run XCP-D on a large dataset that had already been processed with an older version of fMRIPrep (1.4.1). Namely, I'm trying to process the AOMIC-ID1000 data ([doi:10.18112/openneuro.ds003097.v1.2.1](https://doi.org/10.18112/openneuro.ds003097.v1.2.1)). 

### What did you expect to happen?
I was expecting XCP-D to complete the post-processing steps and generate html reports.

### What actually happened?
The pipeline seems to run through as expected and produces the expected outputs. However, XCP-D crashes when generating the qc_report: `could not run node: xcpd_wf.single_subject_0810_wf.nifti_postprocess_0_wf.qc_report_wf.qc_report` with the error `File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item KeyError: 'rmsd'`

This error does not occur when I run the raw data through the latest version of fMRIPrep and then submit it to XCP-D. However, I would like to use the existing version of the preprocessed data as it would be quite computationally demanding to process all 900+ participants from scratch. 

## Reproducing the bug
1. Download data from one participant from OpenNeuro:
```
aws s3 sync --no-sign-request s3://openneuro.org/ds002895ds003097/derivatives/fmriprep/sub-0001/ .
aws s3 sync --no-sign-request s3://openneuro.org/ds002895ds003097/derivatives/freesurfer/sub-0001/ .
```

2. Run the XCP-D with docker (defining the paths according to the download location on the system):
```
docker run --rm -it \
   -v "${fmriprep_folder}":/fmriprep:ro \
   -v "${work_folder}":/work:rw \
    -v "${freesurfer_folder}":/freesurfer:ro \
   -v "${out_folder}":/out:rw \
   -v /home/jmbathe/license.txt:/opt/freesurfer/license.txt \
   pennlinc/xcp_d:latest \
   /fmriprep /out participant \
    --participant_label ${participant_label} \
    --despike \
    --smoothing 6 \
    --fd_thresh 0.3 \
    --lower_bpf 0.01 \
    --upper_bpf 0.08 \
    --bpf_order 2 \
    --fs-license-file /opt/freesurfer/license.txt
```

**Comment by tsalo** [comment]
I'm happy to make a small change if it will support old versions of fMRIPrep, but I want to make sure this isn't just the first of many changes that would need to be made. Can you identify the full set of changes that need to be made? For example, can you add an `rmsd` column to one of your old fMRI confounds files and run XCP-D on it?

**Comment by joebathelt** [comment]
Thank you for the tip. XCP-D does run through everything without error when I include an "rmsd" column in the confound CSV. I also had to change the suffix of the confound files from "_confounds" to "_timeseries" to make XCP-D compatible with the outputs of this older version of fMRIPrep.
