### ISSUE TITLE
skill alff and reho

### ISSUE THREAD

**Issue by chenfei-ye** [PennLINC/xcp_d#1128]
Hi, 

I think many users just need bold timeseries and FC from xcp-d. But alff and reho calculation takes a lot of time. 
I hope alff and reho could be skipped for the next xcp-d version.
Thanks. 

Chenfei

**Comment by tsalo** [comment]
This is already an open conversation about this in #1058, so I'm going to close this issue, but please feel free to follow up in the linked issue.
