### ISSUE TITLE
Inconsistency in Gordon Parcel Names

### ISSUE THREAD

**Issue by erikglee** [PennLINC/xcp_d#1197]
## Summary
The files with names such as sub-<label>_ses-<label>_task-rest_dir-<label>_run-<label>_space-fsLR_atlas-Gordon_coverage.tsv seem to have ambiguous parcel names (such as "Parcel_1", "Parcel_2"). This is in contrast to other Gordon output files, such as the ALFF, ReHo, and timeseries output files that have more specific parcel names (such as "L_Default_1", "L_SMhand_1"). This inconsistency seems to be specific to the Gordon outputs, and not present for other parcellation types.

I noticed this behavior in XCP-D version 0.7.2, so maybe it has already been fixed. Please let me know if you need any other information on my end!

Thanks,
Erik

**Comment by tsalo** [comment]
Just a note- the "Parcel X" nomenclature comes from the parcel names within the CIFTI file, while the meaningful parcel names come from the associated TSV file. Some atlases have interpretable parcel names in the CIFTI files, while others (like Gordon) do not. Typically I try to use the TSV parcel names in output files, but I might not have done that for the coverage files.

**Comment by tsalo** [comment]
I just checked the test outputs from a recent PR and the Gordon coverage file has actual parcel names, so I must have fixed it at some point.
