### ISSUE TITLE
Nibabies (and probably fMRIPrep) will not automatically output native anatomical-space brain mask in future

### ISSUE THREAD

**Issue by tsalo** [PennLINC/xcp_d#1198]
## Summary

The native anatomical-space brain mask is used in two places:

1. Estimating the participant's brain radius for FD calculation when using `--head-radius auto`.
2. In `init_qc_report_wf` --> `QCPlots`, used to calculate coregistration quality by comparing the T1w-space brain mask to the functional-space brain mask warped to T1w space.
    - In `init_qc_report_wf`, it's used to warp the functional-space brain mask to T1w space, which is only used to calculate coregistration quality.

## Next steps

1. Collect a standard-space anatomical brain mask instead.
2. Use the template-to-anat transform to warp the brain mask to native anatomical space.
3. Use the anatomical-space brain mask to calculate the brain radius and coregistration quality.

**Comment by smeisler** [comment]
Sounds good, just a couple of thoughts.

1) I wonder if head radius could be estimated just by the warp information (analogous to using Jacobian determinant for brain volume).
2) For quantitative coregistration quality using a mask, you're probably limited to dice score or simple overlap, right? Would also warping the T1w be better for looking at more nuanced metrics, for example mutual information (which might not work for T1w vs BOLD contrast, but just a thought)?

**Comment by tsalo** [comment]
1. I think that's a great idea, but I have no clue how to go about it.
2. I think we have Dice, overlap, and Pearson correlation. I do think the QC metrics could do with an update. I'll have to read a few papers on newer QC metrics though.

**Comment by tsalo** [comment]
Just starting to work on this now, and I'm seeing a problem with my plan. The subject-specific head radius is estimated in a function, not a Nipype node, so that it can be used (1) to filter out bad runs and (2) within the boilerplate. I'd strongly prefer not to run any non-Python code (or computationally intensive code, for that matter) outside of workflows, but applying the transform to get the brain mask from standard space to native anatomical space requires antsApplyTransforms (or something similar).

**Comment by smeisler** [comment]
You could use antspyx and run `antsApplyTransform` in python: https://antspy.readthedocs.io/en/latest/_modules/ants/registration/apply_transforms.html

**Comment by tsalo** [comment]
If I can't find any way to embed this in a workflow I'll probably do that.
