### ISSUE TITLE
docs ask for invalid Apptainer version

### ISSUE THREAD

**Issue by dmd** [PennLINC/xcp_d#1230]
https://xcp-d.readthedocs.io/en/latest/usage.html#apptainer states:

> XCP-D (and perhaps other Docker-based Apptainer images) may not work with Apptainer <=2.4. We strongly recommend using Apptainer 3+.

However, the [most recent release of Apptainer](https://github.com/apptainer/apptainer/releases) is only v1.3.3.

**Comment by tsalo** [comment]
Ah thanks. I think we just did a find and replace on Singularity to Apptainer and forgot to check the versions.

**Comment by dmd** [comment]
Do you know what version of Apptainer is needed? (I have never had *any* issues running Docker-derived stuff in Apptainer...)

**Comment by tsalo** [comment]
I'm not sure. I think Apptainer may have split out of Singularity after the minimum Singularity version.
