### ISSUE TITLE
Add "27P" and "36P" confound regression options without GSR

### ISSUE THREAD

**Issue by LeonDLotter** [PennLINC/xcp_d#1231]
## Summary
It would be great to have the option to run "27P" and "36P" confound regression *without* global signal regressors. I.e.:
- `27P-nogsr` or `26P`: 24 motion parameters and derivatives + WM + CSF 
- `36P-nogsr` or `32P`: 24 motion parameters and derivatives + 4 WM regressors + 4 CSF regressors

## Additional details
- Benefit for practice: Use when GSR is not wanted or to evaluate the effect of global signal regression
- Consistency within confound regressor options: There are options to run aCompCor and AROMA with and without GSR. Adding such an option to the other regressor sets would feel sensible.

## Next steps
I admit that I did not look deep into your code. However, adding...

```python
# Get rot and trans values, as well as derivatives and square, WM and CSF.
"27P-nogsr": {
    "strategy": ["motion", "wm_csf"],
    "motion": "full",
    "wm_csf": "basic",
},
# Get rot and trans values, as well as derivatives and square, WM, and CSF.
# Add the square and derivative of the WM and CSF.
"36P-nogsr": {
    "strategy": ["motion", "wm_csf"],
    "motion": "full",
    "wm_csf": "full",
},
```

...to [xcp_d/utils/confounds: load_confound_matrix()](https://github.com/PennLINC/xcp_d/blob/main/xcp_d/utils/confounds.py#L177) plus some higher-level adjustments could suffice?

Thanks and thank you a lot for your great work!

**Comment by tsalo** [comment]
Thanks for the idea @LeonDLotter. I'll discuss it with the rest of the team. I can't guarantee that we'll support this, but if we do, then we'll need citations for each strategy you want supported. Preferably from papers that have directly benchmarked these strategies against others.

**Comment by tsalo** [comment]
Sorry for the delay in responding @LeonDLotter. I spoke with @sattertt and @mattcieslak, and I think we have a good way to support what you want without adding more options to XCP-D. Basically, we're going to allow config files that list the columns to use, so users can choose whatever they want.

**Comment by LeonDLotter** [comment]
Hi @tsalo, thanks so much for considering my request and apologies also from my side for the late response. 
Your proposed solution seems very sensible and will surely fit my use cases. Thanks a lot!
