### ISSUE TITLE
FD Thresh arg error

### ISSUE THREAD

**Issue by juansanchezpena** [PennLINC/xcp_d#1302]
## Summary
xcp_d: error: unrecognized arguments: --fd-thresh 0.3
xcp_d: error: ambiguous option: --f could match --file-format, --fd-thresh, --fd_thresh, --fs-license-file

fd_thresh 0.3 WORKED!

## Additional details

- xcp_d version: 0.9.1
- Docker version:24.0.7
- Apptainer version: ?

### What were you trying to do?
fun xcp-d on fmriprep 24.0.1 output:

### What did you expect to happen?
conainer launch
### What actually happened?
errors above until I used fd_thresh

## Reproducing the bug
a " --mode none --participant-label patensasc0085  --input-type fmriprep --file-format cifti --despike  fd_thresh 0.3 -p 36P -m y --motion-filter-type notch  --band-stop-min 12 --band-stop-max 18 --output-type interpolated --min-coverage 0"

**Comment by tsalo** [comment]
Can you share the full command you used that failed, as well as the full command that succeeded?

**Comment by tsalo** [comment]
@juansanchezpena any updates on the `--fd-thresh` problem? If not, I'll close this issue.
