### ISSUE TITLE
why is having multiple surfaces and morphometry files in different sessions a problem?

### ISSUE THREAD

**Issue by cindyhfls** [PennLINC/xcp_d#1313]
In Util/bids.py

There are multiple errors where the same participant have multiple surfaces or morphometry files. I think that's normal for longitudinal sessions to have different surfaces and morphometry files. No? Can we make that a warning not an error?

Also you guys have two many irrelevant anatomical requirements that is contributing to the generation of summary figures (?) but not really used in confound removal (which was stated as the goal). Is it possible to have flag for a simple module that gets rid of all those requirements if the user just want to deal with confounds because they are error-prone...

**Comment by cindyhfls** [comment]
Also I have to add that the BIDSLayout does not recognize the suffix as part of the participant id, which would not be a problem if the original data was in BIDS format but it would be a pain if people used ingression to convert other data formats (I understand that it is rare that you would use it) but it was promoted in the paper as if the pipeline was general-purpose and accommodating for all preprocessing pipelines which it really isn't.

I ended up having to separate my folder name into participant and session part for longitudinal sessions (the original folder name is <participant_id>_V1_MR for visit 1 etc.

**Comment by mattcieslak** [comment]
Hi Cindy, a couple thoughts here 
> There are multiple errors where the same participant have multiple surfaces or morphometry files.

That's just how fMRIprep processes/writes out these files at the moment.  We will support session-wise anatomical data in the near future. There is an existing issue for that though: #1306.

> Also you guys have two many irrelevant anatomical requirements that is contributing to the generation of summary figures (?) but not really used in confound removal (which was stated as the goal).

There was some debate about this, but ultimately xcpd also is used for QC and these files are used for QC by some large ongoing projects. If you don't personally use these outputs, you can always delete them without affecting your confound-removed bold data.

> Also I have to add that the BIDSLayout does not recognize the suffix as part of the participant id, 

I'm not sure I follow - suffixes aren't part of subject IDs. In BIDS "suffix" means the last item before the file extension.

> it was promoted in the paper as if the pipeline was general-purpose and accommodating for all preprocessing pipelines which it really isn't.

In the paper we show how xcpd works with fmriprep, HCP and ABCD-BIDS. It's a BIDS App, and only works on the HCP and ABCD-BIDS inputs by first converting them to BIDS. BIDS is what allows xcpd to correctly process almost any sort of input data (in BIDS) automatically. I'd be very interested in seeing a pipeline that works on arbitrary file names!

> I ended up having to separate my folder name into participant and session part for longitudinal sessions (the original folder name is <participant_id>_V1_MR for visit 1 etc.

Right! That's how BIDS requires longitudinal data be named.

**Comment by mattcieslak** [comment]
Agreed, the session-specific anatomical issues in fmriprep have been a big headache for developmental work.

It sounds like you have some example data that came out of the official HCP pipeline but isn't working well with xcpd's ingressors. We haven't seen these kind of HCP Pipeline inputs - in the paper we only tested on HCP-D and we've tested locally with HCP-YA. Would you be able to work on a PR that would accommodate them? We'd be happy to review.

For the file deletion I was suggesting letting xcpd run completely and then deleting those extra anatomical outputs to save disk space. It sounds like you're having trouble getting your anatomical data into a format that lets these workflows run successfully?

**Comment by cindyhfls** [comment]
yes, my concern is not mainly about disk space. It's more about that those missing file broke the pipeline and it's hard to debug.

**Comment by cindyhfls** [comment]
btw do you think it is possible at all the skip the ingression and fit the required file name structure as a json file? This would be much more efficient in time and space.
