### ISSUE TITLE
HBCD software standards requirements

### ISSUE THREAD

**Issue by LuciMoore** [PennLINC/xcp_d#1332]
The following updates are required to meet Bronze badge status for NMIND review:

- [ ] Provide/generate/point to test data
- [ ] Provide instructions for users to run tests and evaluate for correct behavior

The current checklist submitted for review is here: https://github.com/nmind/proceedings/issues/16

Just let me know if you feel you'll be able to address these points within the next week or not. If the timeline for these updates isn't realistic given the short time frame, then I can have NMIND move forward with the review and you can make updates+resubmit the checklist at a later date to achieve a higher badge rating. so just let me know either way!

For the second item, you could consider pointing to https://cdnis-brain.readthedocs.io/infant-qa/. This outlines the CDNI standards for performing quality control based on executive summary images from abcd-hcp-pipeline, so should work for XCP-D as well. It doesn't necessarily address correct software behavior, but could help users determine whether their outputs look reasonable or not

**Comment by LuciMoore** [comment]
I think that should work, yes. The person who did the initial review must have missed that section. I'll mark these items as complete and indicate to NMIND that XCP-D is ready for final review

**Comment by tsalo** [comment]
I only added it a couple of days ago so it might not have been up when the reviewer looked.
