### ISSUE TITLE
detrend

### ISSUE THREAD

**Issue by Xiuyi-Wang** [PennLINC/xcp_d#241]
Hello deverlopper,

I am writing to confirm whether detrend is done using xcp_abcd by default. It seems like it is done based on the source code but I did not find this info in the method section in the sub-ID.html file. 

The following is the code to do the detrend if I understand correctly.
# xcp_abcd/interfaces/regression.py
# line 78 ~ 80
orderx =np.floor(1+ data_matrix.shape[1]*self.inputs.tr/150)
dd_data = demean_detrend_data(data=data_matrix,TR=self.inputs.tr,order=orderx)
confound = demean_detrend_data(data=confound,TR=self.inputs.tr,order=orderx)

The following is the method section in the sub-ID.html file.
Post-processing of fMRIPrep outputs

For each of the nine CIFTI runs found per subject (across all tasks and sessions), the following post-processing was performed: before nuissance regression and filtering any volumes with framewise-displacement greater than 10.0 mm (Power et al. 2014; Satterthwaite et al. 2013) were flagged as outlier and excluded from nuissance regression. In total, 36 nuisance regressors were selected from the nuisance confound matrices of fMRIPrep output. These nuisance regressors included six motion parameters, global signal, the mean white matter, the mean CSF signal with their temporal derivatives, and the quadratic expansion of six motion parameters, tissues signals and their temporal derivatives (Ciric et al. 2018, 2017; Satterthwaite et al. 2013). These nuisance regressors were regressed from the BOLD data using linear regression - as implemented in Scikit-Learn 0.24.2 (Pedregosa et al. 2011). Residual timeseries from this regression were then band-pass filtered to retain signals within the 0.01-0.08 Hz frequency band. The processed BOLD was smoothed using Connectome Workbench with a gaussian kernel size of 6.0 mm (FWHM).

Many thanks for your confirmation.

Xiuyi

**Comment by a3sha2** [comment]
thank yopu @Xiuyi-Wang , yes there was demean and detrending before nuisance regression. We will update the html report

**Comment by Xiuyi-Wang** [comment]
Many thanks for your confirmation @a3sha2.
