### ISSUE TITLE
CSF duplicated in confound matrix 36p (and no CSF derivative)

### ISSUE THREAD

**Issue by danella** [PennLINC/xcp_d#251]
Hello, when running the 36p model, it seems that the CSF is included twice in the confound matrix (and I believe the derivative is not there). Looking at the code, I am not sure how this is the case - but this appears to be what is in the .tsv file. The power expansion of CSF is also a duplicate. Thanks! (Running :latest on singularity)

**Comment by a3sha2** [comment]
hello @danella 

thank you very much. this is very important and we will be happy if you can help us with your tsv file. 
We will check at our end also and provide you the  update.
