### ISSUE TITLE
[ENH] Combine surface rehos and subcortical reho to scalar/dtseries

### ISSUE THREAD

**Issue by a3sha2** [PennLINC/xcp_d#260]
- [x] Check if this has been implemented

**Comment by tsalo** [comment]
Can we run `wb_command -cifti-separate <cifti_file.dtseries.nii> COLUMN -volume-all <output_file.nii.gz>` to get the subcortical data in nifti format to run ReHo on?

I don't know how to merge the resulting two surface giftis and subcortical nifti into a cifti afterwards though.

**Comment by kahinimehta** [comment]
@tsalo at the moment that's how they are being separated. Not sure how to merge them back either but will look around

**Comment by tsalo** [comment]
I don't think so, since that seems to be for parcellated/metric data. I could be misunderstanding what "metric" means though.

I think we may need to create a NeuroStars post about combining giftis and a nifti into a cifti.

**Comment by kahinimehta** [comment]
@tsalo  looks like `wb_command -cifti-create-dense-scalar sub.sulc.32k.dscalar.nii -left-metric sub.L.sulc.32k.shape.gii -right-metric sub.R.sulc.32k.shape.gii` worked for me
<img width="567" alt="Screen Shot 2022-10-20 at 3 24 07 PM" src="https://user-images.githubusercontent.com/68132139/197039399-97849ac4-81b7-4ec9-b0dd-632ae3661494.png">

**Comment by tsalo** [comment]
Does it work with the subcortical nifti as well?
