### ISSUE TITLE
p_abcd: error: the following arguments are required: analysis_level

### ISSUE THREAD

**Issue by PanagiotisHelios** [PennLINC/xcp_d#269]
Hello,

I would like to denoise my fmri data (intend to do conn analyses). I preprocessed them with fmriprep and want to implement the 24P + acompcor denoising options using the xcp_abcd tool.

I try:

```
singularity --verbose run -B /storage/ /usr/local/bin/xcp_abcd-0.0.8.simg $input_dir $out_dir participant \
--participant_label $subj \
-w $workdir \
-t itemobject \
--smoothing 4 \
-p acompcor \
```

However, I get this error (see bottom line):

`**p_abcd: error: the following arguments are required: analysis_level**`

My goal is to use both acompocor+24P. Did I get right that it should be as follow?

-p {24P,acompcor}

For now I omit this part. However, I tried using 24P only as well (or both 24P+acompcor), but nothing has worked so far, since I get this analysis_level error.

Any help or idea here?

Thank you a lot in advance :slight_smile: ,

Best,
Pan

**Comment by a3sha2** [comment]
Hi Pan, 
You can only choose 24P or acompcor ( acompcor includes 12P as well https://xcp-abcd.readthedocs.io/en/latest/generalworkflow.html) 

for the error, how did you define $input_dir and  $out_dir

**Comment by PanagiotisHelios** [comment]
Actually I managed to make it run, there was indeed a subtle typo. 

But I have a new weird error & some questions that I am not sure about reading the documentation.

I would like to use highpass filter, how can I implement this? (i want to do task conn analyses) Do I understand correctly that by default a band-fass filtering 0.001 to 0.09 Hz is applied (this is the typical for rs-fmri from what I remember). But for task connectivity high-pass filtering is what I need.
-Also FD correction is implemented per default, or I have to include the -f argument?

2) Importantly, I get this error
![Screenshot-iliopoul@ikndnode-0-0 -storage-users-iliopoul-PHD-code-MEMTRAIN2](https://user-images.githubusercontent.com/54393918/146160421-d17e1cd7-e408-430e-96d5-03fdf30a12ff.png)

Sth seems to go wrong under the hood here?

Thank you in advance,

**Comment by a3sha2** [comment]
if you want to use high pass filter, you can set  band-pass filtering to 0.001 to 2/TR (nyquist),
0.3mm is default for FD. 
this error is likely due incomplete fmriprep output, pls check anat directory of fmriprep

**Comment by PanagiotisHelios** [comment]
Hello, I thought to try again make this tool work.

The fmriprep output should be alright since I got all the required files (and preproc ran successfully).

I don't know if that has to do with the more recent fmriprep versions? I saw some problems mentioned in other posts.

Note I have 2 sessions (func) but since anat image is averaged there is only one anat folder. Is this maybe the source of problems?

Please share your wisdom & suggestions.

Thank you :)

**Comment by PanagiotisHelios** [comment]
My code in case it helps:
```
subject=$1 
subj=$subject

singularity --verbose run -B /storage/ /usr/local/bin/xcp_abcd-0.0.8.simg $input_dir $output_dir participant \
--participant_label $subj \
-w $workdir \
-t itemobject \
--smoothing 4 \
-p acompcor \
-f 0.3 \
```

**Comment by a3sha2** [comment]
@PanagiotisHelios  there is bug  with `acompcor` in the 0.0.8 version

pls try the unstable version and let us know `xcp_abcd:unstable`
