### ISSUE TITLE
Interpolation_WF error

### ISSUE THREAD

**Issue by smeisler** [PennLINC/xcp_d#276]
Running the most recent unstable build of XCP ABCD (to use acompcor) on Singularity. Dataset is BIDS valid and preprocessed with fMRIPrep 21.0.0.
## Command
`singularity run -B $scratch,$BIDS $IMG ${BIDS}/derivatives/fmriprep ${BIDS}/derivatives --participant_label $sub -w ${scratch} -f .9 -p acompcor --smoothing 0`

## Error
```
	 [Node] Error on "xcpabcd_wf.single_subject_047EPKL011011_wf.bold_postprocess_1_wf.interpolation_wf" (/om/scratch/Fri/smeisler/xcp_abcd_new/xcpabcd_wf/single_subject_047EPKL011011_wf/bold_postprocess_1_wf/interpolation_wf)
211219-20:03:49,990 nipype.workflow ERROR:
	 Node interpolation_wf failed to run on host node009.cm.cluster.
211219-20:03:49,995 nipype.workflow ERROR:
	 Saving crash info to /om4/group/gablab/data/ds003126/derivatives/xcp_abcd/sub-047EPKL011011/log/crash-20211219-200349-smeisler-interpolation_wf-6c79a4df-c15d-4516-9923-7273a4f2b465.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 521, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 639, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node interpolation_wf.

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 398, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_abcd/interfaces/prepostcleaning.py", line 256, in _run_interface
    recon_data = interpolate_masked_datax(img_datax=fulldata, tmask=tmask,
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_abcd/utils/modified_data.py", line 209, in interpolate_masked_datax
    term_recon[i,:,:] = np.outer(term_prod[i,:],s[i,:])
ValueError: could not broadcast input array from shape (128,1000) into shape (127,1000)
```

**Comment by smeisler** [comment]
I looked at the FD files for subjects who are failing and there are not that many volumes with FD > 0.9. I tried raising FD to a more lenient threshold of 1 and got the same error. I also got the same error setting -f to 0.5.

**Comment by a3sha2** [comment]
pls can you try the latest unstable one, happy new year!

**Comment by smeisler** [comment]
Happy New Year to you too! Unfortunately, I still get this error for some subjects. The dataset I am using is public, so I would not have any issues against sending you a sample of fMRIPrep outputs for failing subjects, if that would help.

**Comment by smeisler** [comment]
Hi @a3sha2, I wanted to follow up on this. I am still getting this error on the newest version and across FD thresholds. I am curious if the errors I am getting are reproducible on your end. I have a zipped archive of an example subject's fMRIPrep outputs. If you would be willing to test on your end, please let me know an email address I should send the data to.

My 21.0.0 fMRIPrep extra arguments were `--use-syn-sdc --force-syn --cifti-output 91k --output-spaces MNI152NLin6Asym:res-2`

My extra XCPD arguments are -`-cifti -p acompcor --despike --motion-filter-type notch --band-stop-min 15 --band-stop-min 25 -f .9`

Thanks,
Steven

**Comment by smeisler** [comment]
This appears to have been fixed in the recent unstable version.
