### ISSUE TITLE
acompcor + filter

### ISSUE THREAD

**Issue by smeisler** [PennLINC/xcp_d#288]
Hello,

According to fMRIPrep documentation:
![image](https://user-images.githubusercontent.com/27028726/151675766-09f231bb-56dc-4347-800e-e3d4906953d1.png)
Does XCP_D incorporate the cosine regressors? If so, does that override other filter settings?

Thanks,
Steven

**Comment by a3sha2** [comment]
@smeisler  we dont use consine_XX

**Comment by a3sha2** [comment]
@mb3152 @mattcieslak ^^^

**Comment by mb3152** [comment]
Hi, thanks @smeisler, I updated XCP to use the cosine regressors. We also have a acompcor_gsr version now, if you are interested. That is what I would use.

**Comment by smeisler** [comment]
Sorry to repoen this issue, but I am getting an error for `UnboundLocalError: local variable 'bsignal' referenced before assignment` when passing in `-p acompcor_gsr` using the latest unstable xcp_d docker container. Is this strategy implemented in the docker version yet?

**Comment by smeisler** [comment]
See PR https://github.com/PennLINC/xcp_d/pull/292
