### ISSUE TITLE
Estimate head/brain size automatically from brain mask

### ISSUE THREAD

**Issue by hough129** [PennLINC/xcp_d#298]
Scale brain size flag based off of the age of the participant. Will need to find or make a table for the best brain size for each age.

We talked about this on slack briefly - adding it here as an issue.

I think we should be able to help find / make a table. We should have a resource we can use through the BCP data.

**Comment by tsalo** [comment]
This might be useful: https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1651-2227.2011.02173.x

**Comment by kahinimehta** [comment]
@tsalo  will have a look eventually

**Comment by tsalo** [comment]
Are there any tools to estimate this from the brain mask?

**Comment by kahinimehta** [comment]
Not that I know of, but could look around

**Comment by tsalo** [comment]
Here's my proposal:

1. Add an `auto` option for the `--head_radius` parameter.
2. If `auto`, load the brain mask, count the number of non-zero voxels, and multiply that count by the voxel volume to get the brain volume in millimeters cubed.
3. Calculate the radius from the volume (`radius = ((3 * volume) / (4 * np.pi)) ** (1 / 3)`).

**Comment by tsalo** [comment]
In the UMN/UPenn meeting last Friday, everyone was on board with adopting this.
