### ISSUE TITLE
[RF] Concatenation

### ISSUE THREAD

**Issue by mb3152** [PennLINC/xcp_d#311]
- [x] Make sure DCAN motion file is produced as we want
- [x] Rename 'concantenation.py' to 'concatenation.py'
- [ ] Change concatenation point to NA 
- [x] https://github.com/PennLINC/xcp_d/issues/329
- [x] Refactor the code
- [x] Test the code
- [x] Merge MVP code into main

**Comment by mattcieslak** [comment]
add option for --concatenate-by

**Comment by kahinimehta** [comment]
fixing concatenate_nifti

**Comment by kahinimehta** [comment]
concatnate_nifti works. Next steps: change concatenation point to NA and concatenate all BOLD files tog. - on hold for now

**Comment by kahinimehta** [comment]
also concatenate by task for hdf5 if not done

**Comment by tsalo** [comment]
What does "Change concatenation point to NA" mean?

**Comment by mattcieslak** [comment]
It's for the plots where a time derivative is displayed. The timepoint where two series are concatenated can have a big spike, but we don't want to see it plotted (I think)

**Comment by tsalo** [comment]
Ah, okay. So NA is a NaN?

**Comment by mattcieslak** [comment]
yes, in R speak

**Comment by kahinimehta** [comment]
@tsalo what would the current status of this issue be?

**Comment by tsalo** [comment]
I think we just need the NaNs between runs and some unit testing.

**Comment by tsalo** [comment]
I've moved the NaN thing to #726.
