### ISSUE TITLE
stronger tests for XCPD

### ISSUE THREAD

**Issue by mb3152** [PennLINC/xcp_d#315]

**Comment by kahinimehta** [comment]
to discuss at informatics: ran with bandpass filter off, but this is untested as of now

**Comment by kahinimehta** [comment]
come up with components + set up meeting to discuss next steps

**Comment by kahinimehta** [comment]
see https://github.com/orgs/PennLINC/projects/6/views/23

**Comment by kahinimehta** [comment]
started testing with FD displacement
