### ISSUE TITLE
traiterror

### ISSUE THREAD

**Issue by andreifoldes** [PennLINC/xcp_d#316]
Greetings,

I ran the latest version -0.0.9  in singularity and got a TraitError

`singularity run --cleanenv --bind /cubric/collab/396_cogdist/bids/derivatives --bind /cubric/collab/396_cogdist/xcp_d --bind /cubric/collab/396_cogdist/tamas_tmp_work /cubric/collab/396_cogdist/tamas_tmp_work/images/xcp_d_0.0.9 /cubric/collab/396_cogdist/bids/derivatives /cubric/collab/396_cogdist/xcp_d --participant-label $1 -f 0.5 -w /cubric/collab/396_cogdist/tamas_tmp_work`

```
    raise TraitError(
traits.trait_errors.TraitError: Each element of the 'transforms' trait of a _ApplyTransformsInputSpec instance must be a pathlike object or string representing an existing file or 'identity', but a value of '/cubric/collab/396_cogdist/bids/derivatives/sub-0421002/ses-1/func/sub-0421002_ses-1_task-rest_acq-axial_run-1_echo-1_from-T1w_to-scanner_mode-image_xfm.txt' <class 'str'> was specified.
```

my subject folders functional content werre generated fmriprep 21.0.2 with the --me-output flag; files in the folder are the following:

sub-0421002_ses-1_task-rest_acq-axial_run-1_desc-confounds_timeseries.json
sub-0421002_ses-1_task-rest_acq-axial_run-1_desc-confounds_timeseries.tsv
sub-0421002_ses-1_task-rest_acq-axial_run-1_echo-1_desc-preproc_bold.json
sub-0421002_ses-1_task-rest_acq-axial_run-1_echo-1_desc-preproc_bold.nii.gz
sub-0421002_ses-1_task-rest_acq-axial_run-1_echo-2_desc-preproc_bold.json
sub-0421002_ses-1_task-rest_acq-axial_run-1_echo-2_desc-preproc_bold.nii.gz
sub-0421002_ses-1_task-rest_acq-axial_run-1_echo-3_desc-preproc_bold.json
sub-0421002_ses-1_task-rest_acq-axial_run-1_echo-3_desc-preproc_bold.nii.gz
sub-0421002_ses-1_task-rest_acq-axial_run-1_from-scanner_to-T1w_mode-image_xfm.txt
sub-0421002_ses-1_task-rest_acq-axial_run-1_from-T1w_to-scanner_mode-image_xfm.txt
sub-0421002_ses-1_task-rest_acq-axial_run-1_space-MNI152NLin2009cAsym_res-2_boldref.nii.gz
sub-0421002_ses-1_task-rest_acq-axial_run-1_space-MNI152NLin2009cAsym_res-2_desc-aparcaseg_dseg.nii.gz
sub-0421002_ses-1_task-rest_acq-axial_run-1_space-MNI152NLin2009cAsym_res-2_desc-aseg_dseg.nii.gz
sub-0421002_ses-1_task-rest_acq-axial_run-1_space-MNI152NLin2009cAsym_res-2_desc-brain_mask.json
sub-0421002_ses-1_task-rest_acq-axial_run-1_space-MNI152NLin2009cAsym_res-2_desc-brain_mask.nii.gz
sub-0421002_ses-1_task-rest_acq-axial_run-1_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.json
sub-0421002_ses-1_task-rest_acq-axial_run-1_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.gz

**Comment by andreifoldes** [comment]
I removed the separate echo files from the folder and now it is working... it seems that its not ignoring them by default.

**Comment by mb3152** [comment]
You can run fmriprep with Tedana on, and it will do the optimal combination of echos. No need to keep the separate echoes in the directory that you pass to XCP-D. Let me know if everything is working well.

**Comment by andreifoldes** [comment]
yea I think that's fine - I used –me-output-echos just in case I needed them later
