### ISSUE TITLE
Missing TianSubcortical atlas from output

### ISSUE THREAD

**Issue by andreifoldes** [PennLINC/xcp_d#317]
Greetings,

is there a way to include the 'TianSubcortical/Tian_Subcortex_S3_3T.nii.gz' in the auto-generated output file list or someway to add using a singularity command?

**Comment by mb3152** [comment]
This is going to be:

_space-fsLR_atlas-subcortical_den-91k_bold.pconn.nii
_space-fsLR_atlas-subcortical_den-91k_bold.ptseries.nii

_space-MNI152NLin2009cAsym_atlas-subcortical_desc-connectivity_bold.tsv
_space-MNI152NLin2009cAsym_atlas-subcortical_desc-timeseries_bold.tsv
