### ISSUE TITLE
Error using aroma or aroma_gsr

### ISSUE THREAD

**Issue by AlexLin95-Neurosurg** [PennLINC/xcp_d#319]
Hello everyone,

I encounter an error when using xcp-d (latest version via docker images) to denoise my data after preprocessing by fmriprep (version 21.0.2 via docker images).

xcp-d works well when I choose ‘acompcor’ as nuisance regressors but it throws an error if I choose ‘aroma’ or ‘aroma_gsr’ pipeline:

Traceback (most recent call last):
File “/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py”, line 67, in run_node
result[“result”] = node.run(updatehash=updatehash)
File “/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py”, line 524, in run
result = self._run_interface(execute=True)
File “/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py”, line 642, in _run_interface
return self._run_command(execute)
File “/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py”, line 750, in _run_command
raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node ConfoundMatrix_wf.

Traceback (most recent call last):
File “/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py”, line 398, in run
runtime = self._run_interface(runtime)
File “/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/interfaces/confound.py”, line 87, in _run_interface
data_matrix = load_confound_matrix(datafile=self.inputs.in_file,
File “/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/utils/confounds.py”, line 181, in load_confound_matrix
return confound
UnboundLocalError: local variable ‘confound’ referenced before assignment

Does anyone have any ideas? Thanks a lot!

Zhengyu

**Comment by mb3152** [comment]
I just fixed this, thanks for noting it!
