### ISSUE TITLE
Make DCAN hdf5 motion file even if a task contains only 1 run

### ISSUE THREAD

**Issue by madisoth** [PennLINC/xcp_d#329]
[In concatenation.py](https://github.com/PennLINC/xcp_d/blob/main/xcp_d/utils/concantenation.py#L117=) , in the case of len(resbold)==1 we still want to run make_DCAN_DF, so we get an hdf5 motion file for tasks with a single run

**Comment by mb3152** [comment]
this is going to need to be done outside concatenation.py, I need this soon so I can do a pull request for it
