### ISSUE TITLE
Output both "fMRIPrep-style" and "HCP-style" midthickness and inflated surfaces

### ISSUE THREAD

**Issue by madisoth** [PennLINC/xcp_d#330]
As of the unstable build from 5/24/22, for fMRIPrep/NiBabies only WM and pial anat surfaces are output.

Ideally we would have both "fMRIPrep-style" and the "HCP-style" midthickness and inflated surfaces. (HCP "inflated" surfaces are derived from the midthickness and is better suited for visualization, whereas fMRIPrep/FreeSurfer "inflated" surfaces and derived from the smoothwm) 

For the fMRIPrep surfaces, the same process used to make the WM/pial surfs should work (starting from the wb_command -surface-apply-affine)

The "HCP-style" surfaces can be made using the process from the HCP script here: https://github.com/DCAN-Labs/DCAN-HCP/blob/master/PostFreeSurfer/scripts/FreeSurfer2CaretConvertAndRegisterNonlinear.sh

**Comment by madisoth** [comment]
Added in #380, with the exception that the FreeSurfer-derived fMRIPrep inflated surface is no longer output

**Comment by tsalo** [comment]
>HCP "inflated" surfaces are derived from the midthickness and is better suited for visualization, whereas fMRIPrep/FreeSurfer "inflated" surfaces and derived from the smoothwm

What are the FreeSurfer surfaces useful for, if not visualization?

**Comment by tsalo** [comment]
Per @madisoth in https://github.com/PennLINC/xcp_d/pull/706#discussion_r1046618769, we _don't_ want/need the fMRIPrep-style surfaces. Closing this as unplanned.
