### ISSUE TITLE
[BUG] Example data on circleci is too big

### ISSUE THREAD

**Issue by mattcieslak** [PennLINC/xcp_d#337]
It looks like there are 3 copies of a full freesurfer dataset in the example data, which makes it take a long time to download.

**Comment by tsalo** [comment]
We could probably add a fetch node to the CircleCI workflow to pull the data used by both NiftiWithFreeSurferTest and CiftiWithFreeSurferTest. Does that sound good?

**Comment by tsalo** [comment]
Is there some kind of scope element to caches? Some way to say that a cache should only last as long as the specific CircleCI run, so I can download the data in one step and use it in another, without blowing up the storage?
