### ISSUE TITLE
refactor and test despiking 

### ISSUE THREAD

**Issue by scovitz** [PennLINC/xcp_d#354]
- [ ] Write detailed docstring
 - [x] change name of node to be more descriptive 
 - [ ] sanity check the workflow,  should happen directly after remove TR 
 - [ ] add pytests for despike
 - [ ] check with Ted if despike vs censor scrub is an either or 
 - [ ] take processing steps in https://xcp-d.readthedocs.io/en/latest/generalworkflow.html?highlight=despiking#processesing-steps and put as comments in bold.py

**Comment by kahinimehta** [comment]
moved to other issue
