### ISSUE TITLE
Rework volume transform from native T1w to MNI152NLin6Asym

### ISSUE THREAD

**Issue by madisoth** [PennLINC/xcp_d#358]
If NiBabies / fMRIPrep is run with "--cifti-output", the anat output will always have a "from-T1w_to-MNI152NLin6Asym" transform. With that, in anatomical.py we can transform volumes from native T1w to MNI152NLin6Asym space without the intermediate transform to MNI152NLin2009cAsym or MNIInfant. 

We will still need to support intermediate transforms for cases where we don't have a MNI152NLin6Asym transform.

Relevant code to anat volume transforms: 
get xfm to intermediate MNI: https://github.com/PennLINC/xcp_d/blob/41bfae518906be08bb0093dd9f5ce792a474413f/xcp_d/utils/bids.py#L229
hardcoded xfm from intermediate to MNI152NLin6Asym; this is incorrect for NiBabies (and possibly also for fMRIPrep; filename suggests it's the inverse of the intended transform?)  https://github.com/PennLINC/xcp_d/blob/41bfae518906be08bb0093dd9f5ce792a474413f/xcp_d/workflow/anatomical.py#L90
applying xfms: https://github.com/PennLINC/xcp_d/blob/41bfae518906be08bb0093dd9f5ce792a474413f/xcp_d/workflow/anatomical.py#L196
https://github.com/PennLINC/xcp_d/blob/41bfae518906be08bb0093dd9f5ce792a474413f/xcp_d/utils/utils.py#L11

**Comment by tsalo** [comment]
This is related to #566. In recent discussions, we decided to double down on defaulting to MNI152NLin6Asym, because that's the space the volumetric atlases are in.

**Comment by tsalo** [comment]
I think this might have been handled over the past couple of months. I will close as completed for now, but please reopen if there are still any problems.
