### ISSUE TITLE
Schaeffer parcellations

### ISSUE THREAD

**Issue by JoanSano** [PennLINC/xcp_d#379]
Dear all,
The Schaeffer parcellations outputed by XCP_D are the same despite having different names. They all have 100 regions instead of 200, 300, ... and so on. I attach the command (in python) that I used right after preprocessing the data with fmriprep. I am wondering whether there is a small issue on the code or if it's me making a mistake somewhere. Any kind of comment or help will be very much appreciate it.
Thanks in advance.

cmd = f"docker run --rm -it -v {fmriprep_output}:/data/ -v {WD_xcpd}:/wkdir -v {output_directory}:/out \
        pennlinc/xcp_d:latest /data /out -w /wkdir -p {NS_regressors} --participant-label {subject} --nthreads {nthreads} > {WD_xcpd}/{subject}.txt"

os.system(cmd)

**Comment by kahinimehta** [comment]
We just pushed a quick fix for this -  could you try running XCP with the 'unstable' tag, and let us know if you are still running into the issue? Thanks!

**Comment by JoanSano** [comment]
I just run the same command again and it works. It outputs all the different networks correctly. @kahinimehta thanks a lot for the follow up!

**Comment by kahinimehta** [comment]
No problem - thanks for reporting the issue!
