### ISSUE TITLE
Check to-MNI transforms for infant or adult brains

### ISSUE THREAD

**Issue by mattcieslak** [PennLINC/xcp_d#381]
Some of the surface/cifti workflows that use MNI transforms may need to check whether NLin6 or Infant transforms are necessary. Initially brought up by @madisoth

**Comment by tsalo** [comment]
AFAIK, the transforms are currently handled correctly. I don't know if this is something I've fixed over the last few months, or if it's referring to something I'm not aware of. I'll close for now, but please reopen if you come across any problems.
