### ISSUE TITLE
Reduce redundant code in nifti and cifti postprocessing workflows

### ISSUE THREAD

**Issue by kahinimehta** [PennLINC/xcp_d#418]
- [ ] A lot of things seem to be redundant/repetitive here - not sure why this is written the way it is? Worth discussing a refactor.

**Comment by tsalo** [comment]
I actually removed the postprocessing workflow at some point. We can revisit combining the BOLD and CIFTI postprocessing workflows, given the amount of redundancy between the two, but we'll need to start from scratch on the merged workflow.
