### ISSUE TITLE
Add and test custom confounds utilities to overall workflow

### ISSUE THREAD

**Issue by kahinimehta** [PennLINC/xcp_d#419]
Adding to workflows:

- [x] Dummytime
- [x] Censorscrub
- [x] Regression
- [x] QC
- [x] Executive summary

Testing

- [x] Dummytime
- [x] Censorscrub
- [x] Regression
- [x] QC
- [x] Executive summary

**Comment by tsalo** [comment]
Look at PNC n-back data for testing.
