### ISSUE TITLE
UnboundLocalError: local variable 'ds_report_about' referenced before assignment

### ISSUE THREAD

**Issue by Heechberri** [PennLINC/xcp_d#423]
Hi guys,

I am trying to run my fmriprep output through the xcp_d postprocessing pipeline and and I have been getting the above error. 

Below is my code: 

disk="/home/jiayi/Desktop"
project_dir=$disk/"Control_EXCI_MRI"
data_dir=$project_dir/"data_fmriprep/test"
output_dir=$project_dir/"data_fsl/data_ICA_resting"
scratch=$output_dir/"scratch"

docker run -it \
-v /$data_dir:/data:ro \
-v /$output_dir/:/out \
-v /$scratch:/scratch \
pennlinc/xcp_d:latest \
/data /out participant -w /scratch -t rest --smoothing 6 \
--cifti \
--despike  \
--head_radius 50 --input fmriprep \
--nuissance-regressors acompcor \
--lower-bpf 0.01 --upper-bpf 0.08 \
--dummytime 6 \
--omp-nthreads 2 \
--mem_gb 20 \
--verbose \
--resource-monitor\

I can't even pass the bids validator step, and I think this error has something to do with the nipreps bids workflow. I understand that fmriprep output files might not be bids compliant, and from my reading, I only included the $sub-id/$ses-id/[modality] outputs from fmriprep, along with the dataset_description.json and .bidsignore generated by fmriprep.

I tried both with and without .bidsignore, it didn't help with the error.

Below is the full terminal output:
220823-12:40:20,14 nipype.workflow IMPORTANT:
	 
    Running xcp_d version 0.1.3+0.g9fec4d8.dirty:
      * fMRI directory path: /data.
      * Participant list: ['EXCI0100', 'EXCI0101'].
      * Run identifier: 20220823-124016_33ef2951-90e3-420f-bdad-2cccb5f4fa15.

    
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/cli/run.py", line 617, in build_workflow
    retval['workflow'] = init_xcpd_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/base.py", line 148, in init_xcpd_wf
    single_subj_wf = init_subject_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/base.py", line 433, in init_subject_wf
    (about, ds_report_about, [('out_report', 'in_file')])])
UnboundLocalError: local variable 'ds_report_about' referenced before assignment

Thank you for your time and help!

**Comment by kahinimehta** [comment]
Hello @Heechberri , thanks for posting your issue. We are attempting to reproduce this problem locally with our datasets. 

First, would it be possible for you to provide some more information about your dataset? Namely:
 
1. Do both the participants you are running XCP on have cifti files?
2. Do these filenames end with 'bold.dtseries.nii'? 
3.  How are these cifti files named? 
4. Is your dataset publicly available?  

Thanks for your patience!

**Comment by Heechberri** [comment]
hi hi @kahinimehta,

I am sorry for all the trouble. Indeed as you expected, the problem was with the --cifti flag. I did not have any cifti data and after removing it everything worked fine. 

I understood the documentation wrongly and plus my lack of understanding of the cifti file format, I thought including the flag would produce outputs in cifti, which will allow me Human Connectom pipeline (wb_command) as suggested by the XCP_d documentation.

Thank you for your time!
Regards,
Vae
