### ISSUE TITLE
[DOC] Documentation edits

### ISSUE THREAD

**Issue by kahinimehta** [PennLINC/xcp_d#432]
- [x] Do we need to standardize the naming of the output - and replace ${space} with consistent variables where needed? 
- [x] Update workflow graphs
- [x] Potentially adopt something like fMRIPrep's [mock_config ](https://github.com/nipreps/fmriprep/blob/91dae68908360ce8ab89d6e43f16a62fd6deb1d2/fmriprep/workflows/tests.py#L33)to handle it all safely.
 - [x] Fix typos
 - [ ] Make sure everything is up to date with the latest changes
 - [ ] Update the flowchart provided

**Comment by tsalo** [comment]
Closing in favor of more specific issues.
