### ISSUE TITLE
Add T1w enhancement back eventually

### ISSUE THREAD

**Issue by kahinimehta** [PennLINC/xcp_d#434]
Removed originally because it was causing malloc errors on the M1.
- [ ] Do we want it back? 
- [ ] How to implement it for max. compatibility?

**Comment by tsalo** [comment]
Given that other steps raise the same errors on M1s (see #515), this could be re-added without causing any specific issues.

What is the value added of the T1w enhancement for users?

**Comment by tsalo** [comment]
Currently, the warped T1ws are really only used for the brainsprite and visualizing results. @madisoth @ericfeczko do you think 3dUnifize is a useful step for your T1w output?

**Comment by tsalo** [comment]
@madisoth @ericfeczko just following up. Do you have thoughts on using 3dUnifize?
