### ISSUE TITLE
Fastsurfer and pre-run Freesurfer compatibility

### ISSUE THREAD

**Issue by jbh1091** [PennLINC/xcp_d#446]
Hello,

Some of the data I want to run through xcp_d has already had surface reconstruction performed before fmriprep. Therefore xcp doesn't see it in the expected fmriprep/sourcedata folder and doesn't work on these subjects. Additionally, I can't manually move the pre-run surfaces into a sourcedata folder I create myself because I don't have root access on my computing environment, and the docker version of fmriprep creates outputs as root. Regenerating the surfaces in fmriprep is technically an option, but would be quite time- and resource-intensive.

An update allowing for the optional specification of a pre-run surfaces folder (e.g. like how fmriprep accepts an --fs-subjects-dir option) would be extremely helpful.

Thanks!

**Comment by kahinimehta** [comment]
Hello! Thanks for letting us know - we have no plans for implementation in XCP at the moment, but regenerating the surfaces in fMRIPrep might be the best option at the moment.
