### ISSUE TITLE
[RF] Move DerivativesDataSink to suitable files

### ISSUE THREAD

**Issue by kahinimehta** [PennLINC/xcp_d#449]
Based off comments in workflow: base.py, bold.py, cifti.py

**Comment by tsalo** [comment]
It looks like the same DerivativesDataSink, with the same `out_path_base` modification, is created independently in several files. Is the original one (`out_path_base='niworkflows'`) used anywhere, or could `out_path_base` just be set to 'xcp_d' in the main version?

**Comment by kahinimehta** [comment]
@tsalo worth discussing when we meet tomorrow!

**Comment by tsalo** [comment]
Also, it looks like `DerivativesDataSink` is defined [in `niworkflows`](https://github.com/nipreps/niworkflows/blob/c202fa84181b166416b1c1c2e8cec65151e70f58/niworkflows/interfaces/bids.py#L324), so, if there aren't any modifications in `xcp_d`'s version, maybe we could just import the original?
