### ISSUE TITLE
UnboundLocalError: local variable 't1w' referenced before assignment

### ISSUE THREAD

**Issue by estephanmoana** [PennLINC/xcp_d#451]
Hello, I'm trying to do a test run of xcp_D on preprocessed data from fMRIPrep and I am running into the error below. Any suggestions on how to proceed? Thank you.

`cn2107:~ moana004$ start_time=`date`; subjID="sub-FM0001"; singularity run --nv --cleanenv --bind="${BIDSderiv}:${BIDSderiv},${FREESURFER_HOME}:${FREESURFER_HOME}" ${HOME}/xcp_d/xcp_d-0.1.3.simg ${BIDSderiv}/${subjID}/func ${BIDSderiv}/func_postprocess participant --participant_label ${subjID} --nthreads 8 --omp-nthreads 8 --input-type fmriprep --cifti --smoothing 3 --despike --nuissance-regressors aroma --work_dir /tmp/tempfiles_xcp_d; end_time=`date`; echo -e "Start: ${start_time}\nEnd: ${end_time}"
220901-10:22:04,403 nipype.workflow IMPORTANT:
	 
    Running xcp_d version 0.1.3+0.g9fec4d8.dirty:
      * fMRI directory path: /home/moanae/shared/project_FM_Gracely_TEST_fmriprep_FM0001/sub-FM0001/func.
      * Participant list: ['FM0001'].
      * Run identifier: 20220901-102203_40220c7c-bf4d-4a50-9a9b-2851b2f87899.

    
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/cli/run.py", line 617, in build_workflow
    retval['workflow'] = init_xcpd_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/base.py", line 148, in init_xcpd_wf
    single_subj_wf = init_subject_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/base.py", line 274, in init_subject_wf
    t1wseg = extract_t1w_seg(subj_data=subj_data)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/utils/bids.py", line 256, in extract_t1w_seg
    return t1w, t1seg
UnboundLocalError: local variable 't1w' referenced before assignment
`

**Comment by estephanmoana** [comment]
1. I believe so. The fmridir is /home/moanae/shared/project_FM_Gracely_TEST_fmriprep_FM0001/sub-FM0001/func, and the folder with anat is /home/moanae/shared/project_FM_Gracely_TEST_fmriprep_FM0001/sub-FM0001/anat. I didn't see in a command line to point to the anat folder though <https://xcp-d.readthedocs.io/en/latest/usage.html#command-line-arguments>. The command I used to call the singularity container was: 
`BIDSorig="${HOME}/project_FM_Gracely/BIDS_output_TEST"; BIDSderiv="/home/moanae/shared/project_FM_Gracely_TEST_fmriprep_FM0001"; start_time=`date`; subjID="sub-FM0001"; singularity run --nv --cleanenv --bind="${BIDSderiv}:${BIDSderiv},${FREESURFER_HOME}:${FREESURFER_HOME}" ${HOME}/xcp_d/xcp_d-0.1.3.simg --participant_label ${subjID} --nthreads 8 --omp-nthreads 8 --input-type fmriprep --cifti --smoothing 3 --despike --nuissance-regressors aroma --work_dir /tmp/tempfiles_xcp_d ${BIDSderiv}/${subjID}/func ${BIDSderiv}/func_postprocess participant; end_time=`date`; echo -e "Start: ${start_time}\nEnd: ${end_time}"`

3. Yes, below is a list of files in the folder  /home/moanae/shared/project_FM_Gracely_TEST_fmriprep_FM0001/sub-FM0001/anat:
`cn2107:~ moana004$ ls /home/moanae/shared/project_FM_Gracely_TEST_fmriprep_FM0001/sub-FM0001/anat
sub-FM0001_run-01_desc-aparcaseg_dseg.nii.gz
sub-FM0001_run-01_desc-aseg_dseg.nii.gz
sub-FM0001_run-01_desc-brain_mask.json
sub-FM0001_run-01_desc-brain_mask.nii.gz
sub-FM0001_run-01_desc-preproc_T1w.json
sub-FM0001_run-01_desc-preproc_T1w.nii.gz
sub-FM0001_run-01_dseg.nii.gz
sub-FM0001_run-01_from-fsnative_to-T1w_mode-image_xfm.txt
sub-FM0001_run-01_from-MNI152NLin2009cAsym_to-T1w_mode-image_xfm.h5
sub-FM0001_run-01_from-MNI152NLin6Asym_to-T1w_mode-image_xfm.h5
sub-FM0001_run-01_from-T1w_to-fsnative_mode-image_xfm.txt
sub-FM0001_run-01_from-T1w_to-MNI152NLin2009cAsym_mode-image_xfm.h5
sub-FM0001_run-01_from-T1w_to-MNI152NLin6Asym_mode-image_xfm.h5
sub-FM0001_run-01_hemi-L_inflated.surf.gii
sub-FM0001_run-01_hemi-L_midthickness.surf.gii
sub-FM0001_run-01_hemi-L_pial.surf.gii
sub-FM0001_run-01_hemi-L_smoothwm.surf.gii
sub-FM0001_run-01_hemi-R_inflated.surf.gii
sub-FM0001_run-01_hemi-R_midthickness.surf.gii
sub-FM0001_run-01_hemi-R_pial.surf.gii
sub-FM0001_run-01_hemi-R_smoothwm.surf.gii
sub-FM0001_run-01_label-CSF_probseg.nii.gz
sub-FM0001_run-01_label-GM_probseg.nii.gz
sub-FM0001_run-01_label-WM_probseg.nii.gz
sub-FM0001_run-01_space-MNI152NLin2009cAsym_desc-brain_mask.json
sub-FM0001_run-01_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz
sub-FM0001_run-01_space-MNI152NLin2009cAsym_desc-preproc_T1w.json
sub-FM0001_run-01_space-MNI152NLin2009cAsym_desc-preproc_T1w.nii.gz
sub-FM0001_run-01_space-MNI152NLin2009cAsym_dseg.nii.gz
sub-FM0001_run-01_space-MNI152NLin2009cAsym_label-CSF_probseg.nii.gz
sub-FM0001_run-01_space-MNI152NLin2009cAsym_label-GM_probseg.nii.gz
sub-FM0001_run-01_space-MNI152NLin2009cAsym_label-WM_probseg.nii.gz
`

**Comment by kahinimehta** [comment]
Hello @estephanmoana! The folder you should be pointing to is `/home/moanae/shared/project_FM_Gracely_TEST_fmriprep_FM0001/sub-FM0001` - could you confirm that this error persists when this is the specified directory?

**Comment by estephanmoana** [comment]
Yes, this did the trick. Thank you for your help!
