### ISSUE TITLE
Take a look at schema files to parse input data

### ISSUE THREAD

**Issue by mattcieslak** [PennLINC/xcp_d#453]
Loading data from various inputs is tough and clunky. We should look at making some schema files for inputs so it's not so hard to maintain

**Comment by tsalo** [comment]
I don't think we'll be able to do this for HCP and DCAN derivatives, except for _after_ the conversion to BIDS Derivatives format. However, I'd really like to pursue this for the BIDS Apps.

One thought- the post-processing steps may depend on what steps were taken in preprocessing. We may need to incorporate some kind of "necessary steps" field and an internal vocabulary for the different post-processing steps.

**Comment by tsalo** [comment]
I've adopted the `io_spec.json` config file format from fMRIPrep. It doesn't use the schema, but I'm going to stick with it until fMRIPrep switches over to a new approach that relies on the schema.
