### ISSUE TITLE
[Q] xcp_d container dependencies version check

### ISSUE THREAD

**Issue by estephanmoana** [PennLINC/xcp_d#460]
Hello, I was wondering if there is an easy way to check the dependencies version for a given xcp_d container. I was looking at the container dependencies for xcp_d version 0.1.3, and it seems that the included FSL version is 5.0.9 - which is from 2015. Is it possible to update the FSL version included in the container? Thank you.

**Comment by tsalo** [comment]
I've opened #524 about dropping FSL.
