### ISSUE TITLE
[RF] In CensorScrub: should we change how the timeseries for Ciftis is being written out?

### ISSUE THREAD

**Issue by kahinimehta** [PennLINC/xcp_d#461]

**Comment by tsalo** [comment]
Could you expand on this? What specifically should be changed?

**Comment by kahinimehta** [comment]
If we have a cifti and scrub 2 volumes from it during the CensorScrub workflow, we just drop the first two steps of the cifti timeseries rather than rewrite the timeseries @tsalo - https://github.com/PennLINC/xcp_d/blob/main/xcp_d/interfaces/prepostcleaning.py#L269

**Comment by kahinimehta** [comment]
@tsalo  would be happy to take a look at this if it's still needed after switching to Nilearn?

**Comment by tsalo** [comment]
We need to check if the cleaned data from nilearn will retain the censored volumes or not, but my personal opinion is that it may not be worth the effort to implement this in xcpd regardless.
