### ISSUE TITLE
[RF] Update workflow graphs in documentation

### ISSUE THREAD

**Issue by kahinimehta** [PennLINC/xcp_d#470]
- [ ] Update code
- [ ] Potentially adopt something like fMRIPrep's [mock_config ](https://github.com/nipreps/fmriprep/blob/91dae68908360ce8ab89d6e43f16a62fd6deb1d2/fmriprep/workflows/tests.py#L33)to handle it all safely.

**Comment by tsalo** [comment]
I think we can avoid using `mock_config` if we stop having files as parameters and just have them as inputs that can be connected within the workflows.
