### ISSUE TITLE
[RF] More formal PR review structure

### ISSUE THREAD

**Issue by kahinimehta** [PennLINC/xcp_d#483]

**Comment by tsalo** [comment]
Some things that tend to help:

- A code coverage status check, to ensure that no one is adding large amounts of untested code.
- Branch protection rules. We could require passing CI and at least one approving review before PRs can be merged. All of the maintainers would retain sufficient permissions to merge regardless of the checks, if they really need to.
- Well-defined maintainer scopes/areas of expertise. Basically, contributors need to know who to request a review from, depending on what parts of the repo they modify.
