### ISSUE TITLE
Remove unused functions and classes

### ISSUE THREAD

**Issue by tsalo** [PennLINC/xcp_d#501]
## Summary

I ran `vulture` on `xcp_d` to see if there was any unused code. Below is the result, split up based on whether it's a workflow, class, or regular function. I know that many of the items listed below may be things we _plan_ on using, but if there are any that aren't actually used (or planned to be used in the near future) I'd love to remove them from the codebase to simplify things.

Pinging @kahinimehta and @madisoth for your thoughts.

### Classes

- [ ] interfaces.c3.C3dAffineTool
- [ ] interfaces.resting_state.ContrastEnhancement
- [ ] interfaces.surfplotting.SurftoVolume
- [ ] interfaces.surfplotting.RegPlot
- [ ] interfaces.workbench.ConvertWarpfield

### Functions

- [ ] cli.version.check_latest
- [ ] cli.version.is_flagged
- [ ] utils.dcan2fmriprep.symlinkfiles
- [ ] utils.filemanip.path_resolve
- [ ] utils.filemanip.fnames_presuffix
- [ ] utils.filemanip.hash_rename
- [ ] utils.filemanip.check_forhash
- [ ] utils.filemanip.check_depends
- [ ] utils.filemanip.save_json
- [ ] utils.filemanip.load_json
- [ ] utils.filemanip.loadcrash
- [ ] utils.filemanip.crash2txt
- [ ] utils.filemanip.read_stream
- [ ] utils.filemanip.savepkl
- [ ] utils.filemanip.write_rst_header
- [ ] utils.filemanip.write_rst_list
- [ ] utils.filemanip.write_rst_dict
- [ ] utils.filemanip.dist_is_editable
- [ ] utils.filemanip.emptydirs
- [ ] utils.filemanip.silentrm
- [ ] utils.filemanip.get_dependencies
- [ ] utils.filemanip.canonicalize_env
- [ ] utils.filemanip.find_files
- [ ] utils.filemanip.find_and_copy_file
- [ ] utils.plot.plot_svg
- [ ] utils.plot.plot_text
- [ ] utils.plot.display_cb
- [ ] utils.sentry.start_ping
- [ ] utils.write_save.edit_ciftinifti
- [ ] workflow.base._pop

**Comment by kahinimehta** [comment]
Worth removing unused code!

**Comment by tsalo** [comment]
@kahinimehta do you know what `init_post_process_wf` is for? It looks like `init_boldpostprocess_wf` and `init_ciftipostprocess_wf` handle the post-processing.

**Comment by tsalo** [comment]
I think this is mostly done after #608 and #609, so I'm going to close it.
