### ISSUE TITLE
Add utils tests

### ISSUE THREAD

**Issue by kahinimehta** [PennLINC/xcp_d#505]
Go through each function in ..utils and add tests for it

**Comment by kahinimehta** [comment]
SPECIFIC NOTES 

For transform functions:
- [ ] get_transform_filex function and get_transform_file function - are all possible spaces accounted for? 
- [ ] update the doc strings and comments to be more accurate
- [ ] Are the transforms happening correctly?

**Comment by tsalo** [comment]
I think we have pretty good coverage of utils at this point. I am going to close this and we can open issues/PRs on a more granular basis.
