### ISSUE TITLE
[RF] Review BIDS compliance of outputs

### ISSUE THREAD

**Issue by tsalo** [PennLINC/xcp_d#517]
## Summary

At a glance, all of the functional derivatives seem to have a `bold` suffix- even things like time series TSV files.

## Additional details

While functional derivatives aren't currently well supported in the main specification, BEP012 has been pretty stable for a while now, and I believe it's been adopted by fMRIPrep. We can refer to https://github.com/bids-standard/bids-specification/pull/519 for inspiration.

**Comment by tsalo** [comment]
- `desc-timeseries_bold.tsv` --> `timeseries.tsv`
- `desc-framewisedisplacement_bold.tsv` --> [`desc-framewisedisplacement_motion.tsv`](https://github.com/bids-standard/bids-specification/blob/788ebf198f2745a6f56cb71b5285c5a179290f1e/src/05-derivatives/05-functional-derivatives.md?plain=1#L243)
- tmask --> [`outliers.tsv`](https://github.com/bids-standard/bids-specification/blob/788ebf198f2745a6f56cb71b5285c5a179290f1e/src/05-derivatives/05-functional-derivatives.md?plain=1#L280)
- `desc-alff_bold` --> [`alff`](https://github.com/bids-standard/bids-specification/blob/788ebf198f2745a6f56cb71b5285c5a179290f1e/src/05-derivatives/05-functional-derivatives.md?plain=1#L36)
- `desc-alff_smooth_bold` --> [`desc-smooth_alff`](https://github.com/bids-standard/bids-specification/blob/788ebf198f2745a6f56cb71b5285c5a179290f1e/src/05-derivatives/05-functional-derivatives.md?plain=1#L36)
- `desc-reho_bold` --> [`reho`](https://github.com/bids-standard/bids-specification/blob/788ebf198f2745a6f56cb71b5285c5a179290f1e/src/05-derivatives/05-functional-derivatives.md?plain=1#L38)
- `desc-reho_smooth_bold` --> [`desc-smooth_reho`](https://github.com/bids-standard/bids-specification/blob/788ebf198f2745a6f56cb71b5285c5a179290f1e/src/05-derivatives/05-functional-derivatives.md?plain=1#L38)
- `desc-residual_bold` --> `desc-denoised_bold`
- `desc-residual_smooth_bold` --> `desc-denoisedSmoothed_bold`
- `desc-qc_bold.csv` --> This isn't BIDS-ish. I'd recommend putting these metrics in the denoised BOLD file's JSON, like MRIQC does. Then `analysis_level = "group"` would collect the outputs into a TSV file at the top of the derivative directory.

**Comment by mattcieslak** [comment]
possibly make a session-level TSV that has all the metrics. Maybe scans.tsv. Maybe roadmap for now

**Comment by kahinimehta** [comment]
Makes sense! Also make the pconn.nii --> to .tsv for cifti correlations
