### ISSUE TITLE
Reimplement executive summary from original code

### ISSUE THREAD

**Issue by kahinimehta** [PennLINC/xcp_d#532]
see #450
- [x] Better visualization? 
- [x] NiPreps workflow?

**Comment by kahinimehta** [comment]
@tsalo do we need any more exec summary updates after the last PR?

**Comment by tsalo** [comment]
I don't think so. We still need to review the differences between the carpet plots in both the nipreps and executive summary reports to see if we want to combine them, but that can go in a separate issue.

**Comment by tsalo** [comment]
I'm going to reimplement the executive summary from the original code at https://github.com/DCAN-Labs/ExecutiveSummary.

**Comment by tsalo** [comment]
Should have been closed by #702.
