### ISSUE TITLE
[RF, FIX] Conn matrix .tsvs are comma separated

### ISSUE THREAD

**Issue by kahinimehta** [PennLINC/xcp_d#536]
- [x] Make sure the matrixes are tab-separated values

**Comment by tsalo** [comment]
I also noticed that many TSV files don't have headers. They should. Pretty much the only TSV files without headers in BIDS are TSV.GZ (compressed TSV) files for large time series like physio data. We should add the headers, along with JSONs that describe the column names.

**Comment by tsalo** [comment]
Actually, per [BEP017](https://docs.google.com/document/d/1ugBdUF6dhElXdj3u9vw0iWjE6f_Bibsro3ah7sRV0GA/edit#), the conmat TSV format doesn't include an index or header, so it depends on whether we're talking about the correlation matrices or the time series.
