### ISSUE TITLE
Remainder CIFTI Testing

### ISSUE THREAD

**Issue by kahinimehta** [PennLINC/xcp_d#544]
1. Edge cases for Cifti Parcellation
2. CiFTI Smoothing

**Comment by tsalo** [comment]
A couple of possible edge cases to test:
- The atlas and the data have different densities, or are in different spaces
- The atlas contains labels that only appear on vertices that the data do not cover (i.e., not all of the labels in the atlas appear in the BOLD data)
- CIFTI atlases with volumetric subcortical data

**Comment by kahinimehta** [comment]
@tsalo happy to take a look at this later
