### ISSUE TITLE
Track provenance of derived files

### ISSUE THREAD

**Issue by tsalo** [PennLINC/xcp_d#548]
## Summary

BIDS Derivatives includes fields to link derived files to earlier ones (e.g., the preprocessed fMRIPrep file) and the originals in the raw dataset. We should attempt to track this information and include it in `xcp_d`'s sidecar files.

**Comment by sattertt** [comment]
Very good call^^

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Taylor Salo ***@***.***>
Sent: Saturday, October 1, 2022 9:30:49 AM
To: PennLINC/xcp_d ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] [PennLINC/xcp_d] Track provenance of derived files (Issue #548)


Summary

BIDS Derivatives includes fields to link derived files to earlier ones (e.g., the preprocessed fMRIPrep file) and the originals in the raw dataset. We should attempt to track this information and include it in xcp_d's sidecar files.

**Comment by tsalo** [comment]
I think the best way to handle it is this:

1. Set the `BIDSVersion` in dataset_description.json to 1.8.0 (first release after addition of BIDS URIs).
2. Add `DatasetLinks` field to dataset_description.json pointing to preprocessed derivatives (e.g., `"fmriprep": "relative/path/"`). I think we'll need some fancy logic to determine the relative path though...
3. Use BIDS URIs for `Sources` field in sidecar files. E.g., `bids:fmriprep:sub-01/ses-01/func/sub-01_ses-01_task-rest_desc-preproc_bold.nii.gz`.
4. Retain metadata from source files, when available.

**Comment by tsalo** [comment]
I probably should have closed this with #966.
