### ISSUE TITLE
Harmonize atlases across XCP, QSIPrep

### ISSUE THREAD

**Issue by kahinimehta** [PennLINC/xcp_d#551]
Duplicate of https://github.com/PennLINC/informatics_misc/issues/49
- [x] Arrange meeting with @mattcieslak and @tsalo 
- [x] Check xcpd surface atlases against qsiprep volumetric atlases.
- [ ] Make atlases more templateflow-y/BIDS-y in Box folders.
- [ ] Ensure discrete segmentation atlases have data in int16.
- [ ] Add surface atlases to Box folders.
- [ ] Build atlases into Docker image, using Box URLs.
- [ ] Remove atlases xcp_d data folder.
- [x] Create time series files for the different subcortical atlases separately.
- [x] Create specific combined connectivity matrices between subcort and cort atlases based on qsiprep's outputs.
- [ ] Try to back-prune the data folder in git history to reduce size of the repository. (low priority)
- [x] @kahinimehta: check the order of regions, then map the surface-based XCP regions to the QSIprep order if needed (crossref the atlas config file in QSIprep and .dlabel/ node order info in XCP) - don't seem to be matching up at the moment....

**Comment by tsalo** [comment]
Notes from meeting today:

1. Upload NLin6-1x1x1 versions of all atlases we want to the Box xcpd folder.
2. Upload fsLR-32k versions of all atlases, preferably with separate files for cortical and subcortical atlases to the same folder. This may require some work to get the subcortical atlases in this format.
3. Come up with a good format for metadata, node labels, and network labels. qsiprep currently uses a single JSON file for all atlases, xcpd uses text files (.1D),  templateflow uses TSV files. Basically, there's room to standardize. The BIDS Atlas BEP is very unstable and may not be worth adhering to.
4. Write code to do the following:
    1. Combine NLin6 cortical and subcortical atlases, per qsiprep's requirements.
    2. Combine the associated metadata and label files, as needed.
    3. Warp the combined NLin6 nifti atlases to 2009c space.
    4. ~~Enforce LPS+ orientation.~~
    5. Write the new expanded atlases and their sidecar files to the qsiprep Box folder.
10. Upload the code to the code Box folder.
11. Update the Box URL in the qsiprep Docker image.
12. Update the xcpd Docker image to download the atlases from the xcpd Box folder.
13. Remove the atlases from the xcpd repo.
14. Update xcpd to combine atlases as needed. This may require some work to use the new subcortical CIFTI atlases.

**Comment by kahinimehta** [comment]
- [ ] In progress: find/ make appropriate transforms from TemplateFlow github code

**Comment by tsalo** [comment]
AtlasPack is now deploying to DockerHub (https://hub.docker.com/r/pennlinc/atlaspack/tags), so I can start incorporating our new atlases into XCP-D.

**Comment by tsalo** [comment]
I think the question is whether we want to replace the current Schaefer atlases with the new combined atlases, or simply add the new atlases on top of the old ones instead. I'd prefer to just replace the atlases, since the Schaefers are included in the new combined atlases (and thus the Schaefers are redundant on their own), but others may feel more strongly about this.
