### ISSUE TITLE
[RF] Typos in input-type

### ISSUE THREAD

**Issue by kahinimehta** [PennLINC/xcp_d#554]
- [ ] input-type --> input_type? -- @tsalo what do you think? 
- [ ] hpc --> hcp

**Comment by tsalo** [comment]
CLI arguments often include hyphens that are then changed to underscores when the arguments are converted to variables, so I don't see an issue with `input-type`. It might be nice to support `input_type` as well, though.

The `hpc` thing is a great catch!
