### ISSUE TITLE
Add `--disable-executive-summary` option

### ISSUE THREAD

**Issue by kahinimehta** [PennLINC/xcp_d#565]

**Comment by tsalo** [comment]
We want to keep generating the executive summary by default, but, given the maintenance costs of that code, we also want to ensure that anyone who stumbles across a bug can still run xcpd.

We will also work to add all of the figures in the executive summary into the main report over time, so no information is lost and the executive summary becomes more a matter of preferred report organization than content.

**Comment by kahinimehta** [comment]
When bandpass filter is disabled, disable ALFF too
