### ISSUE TITLE
[RF] Parse one output space type via flag

### ISSUE THREAD

**Issue by kahinimehta** [PennLINC/xcp_d#566]
Order of priority: 
1. Check value of `output-space` parameter first.
    1. If there is a value, look for preprocessed derivatives in that space.
    2. If they don't exist, raise an error. 
    3. If they do, post-process the data in that space.
2. If `output-space` isn't defined, check for `MNI152NLin6Asym` space data.
    1. If there is data in this space, post-process it.
    2. If there isn't, try to warp available data to this space as part of the workflow.
    3. If data can't be warped to `MNI152NLin6Asym` space, raise an error. It would be useful for the error to include a list of available spaces, based on the preprocessed data.

We'll need to parse fMRIPrep space strings (e.g., `MNIPediatricAsym:res-1:cohort-2`) to extract all of the relevant entities needed for selecting files.

**Comment by tsalo** [comment]
Regarding space string parsing, we may need [`niworkflows.utils.spaces.OutputReferencesAction`](https://github.com/nipreps/niworkflows/blob/32a33d61ab64e262a4ebcf8afcf232d70c2f92b3/niworkflows/utils/spaces.py#L686) to standardize the strings from the command-line argument, along with [`niworkflows.utils.spaces.Reference`](https://github.com/nipreps/niworkflows/blob/32a33d61ab64e262a4ebcf8afcf232d70c2f92b3/niworkflows/utils/spaces.py#L59) and [`niworkflows.utils.spaces.SpatialReferences`](https://github.com/nipreps/niworkflows/blob/32a33d61ab64e262a4ebcf8afcf232d70c2f92b3/niworkflows/utils/spaces.py#L339) to manage the references. I don't really know how the latter two classes are used yet, so I'll need to dig through the code at some point.

**Comment by tsalo** [comment]
Users can now provide this information via the bids filter file, so I don't know if we need a separate flag.

**Comment by tsalo** [comment]
Per yesterday's informatics call, we're fine closing this.
