### ISSUE TITLE
Leverage nilearn for denoising

### ISSUE THREAD

**Issue by tsalo** [PennLINC/xcp_d#573]
## Summary
Nilearn's `image.clean_img` and `signal.clean` can perform the following steps in one pass:

1. Temporal masking/censoring
2. Bandpass filtering with butterworth or cosine filters.
3. Confound regression.
4. Detrending.

Also, NiftiLabelsMasker can apply the same steps, along with smoothing.

`interfaces.fmriprep.load_confounds` can also load fMRIPrep confounds according to different denoising strategies (i.e., parameter sets).

The one problem is that nilearn doesn't play well with CIFTI data yet, so we still need Connectome WB. I'd like to push as much Python CIFTI I/O work up to nilearn as we can though.

**Comment by tsalo** [comment]
Currently, there seems to be a problem with nilearn's censoring+regression procedure (see https://github.com/nilearn/nilearn/issues/3364), so we may need to wait for a fix.

**Comment by tsalo** [comment]
Thanks @htwangtw. We aren't using `load_confounds` yet, but I'm planning to bring that up soon.

**Comment by htwangtw** [comment]
If you are planning to use cosine filter, I can provide a temporary fix that will be easy to plug out after the fix! Let me know!

**Comment by tsalo** [comment]
One problem- the current version of brainsprite doesn't work with the current version of nilearn:

```
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/utils/execsummary.py", line 10, in <module>
    from brainsprite import viewer_substitute
  File "/usr/local/miniconda/lib/python3.8/site-packages/brainsprite/__init__.py", line 2, in <module>
    from .brainsprite import viewer_substitute
  File "/usr/local/miniconda/lib/python3.8/site-packages/brainsprite/brainsprite.py", line 20, in <module>
    from nilearn.reporting import HTMLDocument
ImportError: cannot import name 'HTMLDocument' from 'nilearn.reporting' (/usr/local/miniconda/lib/python3.8/site-packages/nilearn/reporting/__init__.py)
```

I may need to open an issue in the brainsprite repo.

**Comment by tsalo** [comment]
Here, I'll try to summarize the changes we will need to make if we want to use Nilearn for denoising:

1. Remove `CensorScrub`- Nilearn handles censoring automatically with its `sample_mask` option.
2. Remove `Regress`- Nilearn would do the denoising.
3. Perform despiking _before_ the denoising. Currently it happens before regression, but _after_ censoring. This isn't possible in Nilearn.
4. Remove `Interpolate`- Nilearn handles the interpolation.
5. Remove `FilteringData`- Nilearn handles the bandpass filtering in the denoising function.
    - This means that we can't use the custom zero-padding length/type (which is, btw, arbitrary), as Nilearn just uses the default scipy padding length/type (also arbitrary, but at least standardized).
6. Drop `bpf_order` parameter- Nilearn hardcodes the bandpass filter order (see #618).

**Comment by tsalo** [comment]
One thing I didn't realize was that nilearn doesn't produce an interpolated version of the denoised data. Unfortunately, interpolating the censored data after filtering won't produce the same result as not censoring the filtered data.

**Comment by tsalo** [comment]
Can't use `nilearn.signal.clean` with the way the DCAN folks want denoising done.
