### ISSUE TITLE
[TEST] HCP and NiBabies workflows

### ISSUE THREAD

**Issue by kahinimehta** [PennLINC/xcp_d#582]
- [x]  Try to get data - Ted to follow up

**Comment by tsalo** [comment]
I was able to use datalad to grab nibabies data from https://gin.g-node.org/nipreps-data/bcp-derivatives and https://gin.g-node.org/nipreps-data/bcp. We can probably use this data for our Nibabies test.

**Comment by tsalo** [comment]
I've uploaded the BCP raw data, regular derivatives, and nibabies derivatives to Box at https://upenn.box.com/s/a4evzxqynozyeyxl1l807kr17oqfufsq.

**Comment by kahinimehta** [comment]
- [ ] Add nibabies test
- [ ] Debug test: why can't pkgrf be found? 
- [ ] Add an outputs.txt to check all teh outputs are present

**Comment by kahinimehta** [comment]
Would be interested in this!

**Comment by kahinimehta** [comment]
HCP Ingression works - need to add tests
