### ISSUE TITLE
[BUG] Output confounds/ combine confound description step

### ISSUE THREAD

**Issue by kahinimehta** [PennLINC/xcp_d#597]
We will still want to either output the selected regressors in a file or combine the confound loading and confound description generation code in one step, so there isn't any chance of undocumented mismatch between them in the future; see #596

**Comment by tsalo** [comment]
We can work off of [this unnumbered BEP](https://docs.google.com/document/d/1KHzp-yk8KXvkUIhtN71WU0m4P4kKT9C1yvI-i9_kNeY/edit), which is based on fitlins's outputs.

**Comment by tsalo** [comment]
Also, I think this will be easier with #610. I'm adding a node that creates the combined+reduced confounds TSV, so the output from this node can be fed directly to the derivatives workflow.

**Comment by kahinimehta** [comment]
@tsalo  if this isn't done/ we don't want to wait for #610 I wouldn't mind having a stab at this.

**Comment by tsalo** [comment]
That would be great. I recommend starting by pulling the `consolidate_confounds` code from #610 and using that.
