### ISSUE TITLE
Test `load_aroma`

### ISSUE THREAD

**Issue by kahinimehta** [PennLINC/xcp_d#598]
Test the `load_aroma` function

**Comment by tsalo** [comment]
At a glance, it looks like `load_aroma` drops the _noise_ columns from the MELODIC mixing matrix, instead of the signal columns:

https://github.com/PennLINC/xcp_d/blob/46c71f71340945b2e36f4744c99d80daade38213/xcp_d/utils/confounds.py#L449-L460

**Comment by tsalo** [comment]
Now that #698 has been merged, we can definitely test `load_aroma`.
