### ISSUE TITLE
[RF] Change BrainSprites as discussed

### ISSUE THREAD

**Issue by kahinimehta** [PennLINC/xcp_d#645]

**Comment by tsalo** [comment]
My understanding:

DCAN have a bash script to make a wbcommand-based montage to use to create a better surface brainsprite.
They want to output individual slices from this for swipes for science app as well.

**Comment by kahinimehta** [comment]
Can we translate this into Python? @tsalo

**Comment by tsalo** [comment]
Yeah, we can.

**Comment by mattcieslak** [comment]
It is probably not going to be worth translating this into python. We should just let their script do its thing, maybe wrapping the shell script itself in a nipype node.

**Comment by tsalo** [comment]
Since we need to ensure that this is enabled by an optional flag, what should we use by default?

**Comment by mattcieslak** [comment]
I was thinking something like `--dcan-qc`

**Comment by tsalo** [comment]
I like that flag, but what should we have in place of the brainsprite when users don't call it?
