### ISSUE TITLE
Should xcpd allow users to disable bandpass filtering?

### ISSUE THREAD

**Issue by mattcieslak** [PennLINC/xcp_d#652]
xcpd has a bandpass-filter parameter that accepts a boolean, which means that users can add `--bandpass-filter False` if they want. I assumed that was a reasonable input, so I created a more straightforward `--disable-bandpass-filter` parameter recently. However, per the discussion in the pennlinc_fmri channel, disabling the bandpass filter invalidates ALFF. Which would be preferable: (1) allow users to disable the bandpass filter, but don't calculate ALFF if the filter is disabled, or (2) remove any options that disable the bandpass filter?

**Comment by tsalo** [comment]
Handled in #628.
