### ISSUE TITLE
TemplateFlow has different entities in their BIDSLayout config

### ISSUE THREAD

**Issue by kahinimehta** [PennLINC/xcp_d#653]
This is causing ReHo/ALFF plotting to throw an error - we need to map between different versions of the entity names; "resolution" instead of "res", "density" instead of "den", and "description" instead of "desc".

**Comment by tsalo** [comment]
It looks like there's currently a typo in their config, so they actually use "desc" even though "description" is the defined entity.

**Comment by tsalo** [comment]
One note: This bug should only surface when the user wants NIFTI outputs, and there is a resolution key in the filenames.
