### ISSUE TITLE
List of questions for xcpd ES

### ISSUE THREAD

**Issue by mattcieslak** [PennLINC/xcp_d#665]
- Should we change the x,y,z to actual coordinates?
 - What are the surfaces/volumes used in the brainsprites
 - Units for FD (mm/sec instead of mm)?
 - What edge detection was used to get the contours?
 - What is the typical workflow? How do raters interact with it?
 - The contour plots are kinda ugly - how about a before/after?
 - Do we want to duplicate so much info in the carpetplots?
- Are the y-axis limits in the DVARS, WB, and FD line plots hardcoded? Are the limits meaningful in some way?
- Is the "Post reg" DVARS line important? Why not just have "Pre reg" and "Post all"?

**Comment by tsalo** [comment]
- Are the y-axis limits in the DVARS, WB, and FD line plots hardcoded? Are the limits meaningful in some way?
- Is the "Post reg" DVARS line important? Why not just have "Pre reg" and "Post all"?

**Comment by tsalo** [comment]
Closing in favor of more targeted issues.
