### ISSUE TITLE
Leverage nilearn for confound selection

### ISSUE THREAD

**Issue by tsalo** [PennLINC/xcp_d#671]
## Summary
Let's take a hard look at [`nilearn.interfaces.fmriprep.load_confounds`](https://nilearn.github.io/stable/modules/generated/nilearn.interfaces.fmriprep.load_confounds.html) to see if we can use it for confound selection.

## Additional details
It would simplify the xcp_d codebase, and could open up more confound strategies to users.

## Next steps

1. Compare load_confounds confound selection options to options in xcp_d.
2. Use load_confounds if it supports everything xcp_d does.

**Comment by tsalo** [comment]
We would need to override their sample mask since they don't use the motion filtering we do, but that's awesome news!

>The only part I'm not sure of is the compcor - do we do anat_combined?

I think we use `anat_separated`, since we grab WM and CSF aCompCor regressors separately.

**Comment by kahinimehta** [comment]
Ahh okay - either way, we should then be good to go!

**Comment by tsalo** [comment]
Do you want to try switching over in a PR?
