### ISSUE TITLE
Convert workflow tests into pytests

### ISSUE THREAD

**Issue by tsalo** [PennLINC/xcp_d#672]
## Summary
I would like to try converting our workflow tests into Python so we can use them in the pytest framework. It's totally fine if that's not feasible though.

## Additional details

The workflow tests would be included in coverage evaluation.

**Comment by mattcieslak** [comment]
I'd like to do this in qsiprep as well. I think the only way to do it is to write tests for each component and string them together. Could be worth brainstorming this together

**Comment by tsalo** [comment]
I was thinking of calling the workflow directly in Python, but that won't test the argument parser and all of the extra stuff in `cli/run.py`.

**Comment by tsalo** [comment]
This might be doable, actually. I just need to add `args=None` to `main`.
