### ISSUE TITLE
filtering by session

### ISSUE THREAD

**Issue by poldrack** [PennLINC/xcp_d#685]
## Summary
it would be very useful to be able to filter by session, for datasets like MyConnectome with many sessions for one participant.

## Next steps
This is enabled in fMRIPrep using the `--bids-filter-file` argument, which has the added benefit of being able to filter on a much larger set of features.  Would it be possible to enable that kind of filtering in XCP-D?

**Comment by tsalo** [comment]
Definitely possible. We already had most of the machinery in place, so it is just a matter of adding the parameter. I've opened a PR with the new feature, and I'll start testing it out on Monday.k

**Comment by poldrack** [comment]
many thanks!

**Comment by tsalo** [comment]
No problem. I'll try to make a release (maybe 0.3.1) later this week.
