### ISSUE TITLE
Parcel-wise coverage checking

### ISSUE THREAD

**Issue by sattertt** [PennLINC/xcp_d#700]
## Summary
In prior versions of XCP, we checked coverage of each parcel in an atlas vs. the functional mask; if it was <50% coverage the timeseries was given NAs (and then reflected in downstream connectivity matricies).  I am not sure how this is handled now in the nifti workflow.  Separately, I am unsure how ciftis handles this issue in general (incomplete coverage).  This tends to be a big issue in large datasets with tight FOVs where coverage of dorsal/ventral brain regions (esp cerebellum, temporal horn, vertex) is often missing. 

## Next steps
a) review how the nifti workflow handles this and consider re-implementing this feature if not present
b) learn how ciftis handle incomplete coverage.

**Comment by tsalo** [comment]
>a) review how the nifti workflow handles this and consider re-implementing this feature if not present

I think NiftiLabelsMasker will just use regular mean, which means that any NaNs in a parcel will result in NaNs for the average time series for that parcel.

>b) learn how ciftis handle incomplete coverage.

I'll have to test that.

**Comment by tsalo** [comment]
Action item: Use the brain mask in the NiftiLabelsMasker initialization. Also, see what the brain mask does.

**Comment by tsalo** [comment]
#733 adds the brain mask to the NIFTI connectivity workflow. It's definitely the right thing to do. If any regions are entirely outside the mask, then the resulting time series will be all zeros.

**Comment by mattcieslak** [comment]
Do an average of ones and zeros to see if there is sufficient coverage of nonzero values in the parcel. If less than 0.5 average in the parcel.

**Comment by tsalo** [comment]
Closing in favor of #756.
