### ISSUE TITLE
init_t1w_wf uses MNI152NLin6Asym as reference regardless of space

### ISSUE THREAD

**Issue by tsalo** [PennLINC/xcp_d#701]
I checked the output more closely and looks like the MNI6 template is still being used as the reference, even when the transform applied is MNIInfant

This was the command.txt for t1w_transform:  

`antsApplyTransforms --default-value 0 --dimensionality 3 --float 0 --input /data/sub-patient01/ses-01/anat/sub-patient01_ses-01_desc-preproc_T1w.nii.gz --input-image-type 3 --interpolation LanczosWindowedSinc --output /work/xcpd_wf/single_subject_patient01_wf/t1w_wf/t1w_transform/sub-patient01_ses-01_desc-preproc_T1w_trans.nii.gz --reference-image /home/feczk001/tmadison/.cache/templateflow/tpl-MNI152NLin6Asym/tpl-MNI152NLin6Asym_res-02_T1w.nii.gz --transform /data/sub-patient01/ses-01/anat/sub-patient01_ses-01_from-T1w_to-MNIInfant+9_mode-image_xfm.h5`

_Originally posted by @madisoth in https://github.com/PennLINC/xcp_d/issues/684#issuecomment-1334542245_

**Comment by tsalo** [comment]
@madisoth a few questions:

1. Is there any situation where the T1w wouldn't already be available in the target space? AFAIK, fMRIPrep (and presumably Nibabies) will output the T1w in the same standard space as the preprocessed BOLD files.
2. What resolution do you expect these files to be in? The same as the BOLD data? 2mm3? Native T1w resolution?

**Comment by tsalo** [comment]
@madisoth I have an additional question. Were you running xcpd with the `--cifti` flag? If so, shouldn't the output space be MNI152NLin6Asym even if the output space for CIFTIs was MNIInfant?

This is related to https://github.com/PennLINC/xcp_d/pull/706#discussion_r1044607456.

**Comment by tsalo** [comment]
It seems like we should use MNI152NLin6Asym whenever the `--cifti` flag is used, and the same template as the BOLD data when it's not.

**Comment by madisoth** [comment]
[> ](https://github.com/PennLINC/xcp_d/issues/701#issuecomment-1335319321)

1) fMRIPrep with --cifti-output flag does not output an MNI6 T1w volume, even though it will always output the T1w-to-MNI6 transform
2) For the BrainSprite we'll want 1mm, and for visualizing with the subcortical BOLD overlaid we will also want 2mm

For the additional question I can confirm I was using --cifti

**Comment by tsalo** [comment]
xcp-d needs a specific trigger case, where if you ran cifti in fMRIPrep and are running cifti in xcp-d and there _isn't_ an MNI152NLin6-space T1w, then the transform must be applied. Might need a separate workflow.

Output 1mm resolution T1w.

**Comment by tsalo** [comment]
Closing this after merging #759. Please reopen if the problem persists.
