### ISSUE TITLE
Use native-space surface files in brainsprite when standard-space ones are unavailable

### ISSUE THREAD

**Issue by kahinimehta** [PennLINC/xcp_d#704]
aparc+aseg files are used as 'dseg' in the HCP and DCAN workflows - but we are not sure if these are appropriate to use in the fMRIPrep and Nibabies workflows. We need to make sure that the brainsprite works with an aparc+aseg file.

**Comment by ericfeczko** [comment]
This doesn't make any sense to me -- the brainsprite viewer should be working directly to visualize the surfaces themselves on top of the anatomical images -- there should be no reason to use a ribbon or segmentation file. 

In fact, I recommend against it as it will lead to inaccurate viewing of the surfaces on the volumes.

**Comment by tsalo** [comment]
The updated plan (thanks @ericfeczko) is to have three possible routes:

1. Native-space surface files are available, and the user has included the `--warp-surfaces-native2std` flag. In this scenario, we'll take the standard-space surfaces from the anatomical workflow (post-#706) and plot those on the standard-space T1w image.
2. Native-space surface files are available, but the user has **not** included the `--warp-surfaces-native2std` flag. In this case, we'll take the native-space surfaces and plot those on top of the native-space T1w image.
3. Surface files are not available (e.g., the user ran fMRIPrep with `--fs-no-reconall`). In this situation, we just won't make the brainsprite.

**Comment by tsalo** [comment]
I'm not sure if the scene files will work with native-space surfaces/T1w. We'll have to see.

**Comment by ericfeczko** [comment]
Interesting -- I'd check with Robert Hermosillo; workbench shouldn't have any issues with loading native surfaces though.
