### ISSUE TITLE
Fix and test HCP ingression

### ISSUE THREAD

**Issue by kahinimehta** [PennLINC/xcp_d#709]
Various issues to be fixed in HCP Ingression: 
As per #703 
- [x] Drop the hack we use to find the boldref file in bids.py for HCP data
- [x] `load_confounds` prepends the first value when reading in confounds, we prepend 0
- [x] Rename the CSF and WM masks we have packaged with xcpd to be more informative. What space are they in? What is their resolution? Where did they come from?
- [x] The HCP transform files are just the preprocessed T1w file. This doesn't make sense.
- [x] The HCP surface files are already in standard space and their filenames should reflect this. We don't know if they're "HCP-style" or not (though they probably are).
- [x] Test on more data on CBICA
- [x] Make the code more generalizable/ readable
- [x] There is a lot of string concatenation when pathlib or os.path should be used.
- [x] Session is hardcoded into the converters.
- [x] The function names (e.g., `dcan2fmriprep` and `dcan2fmriprepx`) are not distinguishable or informative.
- [ ] There may be a fair amount of duplication between the functions.

**Comment by kahinimehta** [comment]
- [ ] Attempting to get access to an HCP-D subject

**Comment by kahinimehta** [comment]
- [ ] Running on all of HCP-YA

**Comment by tsalo** [comment]
#848 _should_ get XCP-D working with HCP-YA data, but I want to wait to close this until after @kahinimehta has had a chance to run it on a larger sample of subjects.
