### ISSUE TITLE
XCP Writing

### ISSUE THREAD

**Issue by kahinimehta** [PennLINC/xcp_d#717]
ITEMS FOR REVISION: 

- [ ] Add NMIND checklist 
- [ ] Add new atlas as requested by Damien: Hermasillo
- [ ] Comments from Chris

**Comment by kahinimehta** [comment]
Will address Taylor's comments soon

**Comment by kahinimehta** [comment]
XCP Methods Section:
200 of each pipeline:

- [ ] HCPYA (Talk to Golia)
- [ ] ABCD (Talk to Arielle)
- [ ] PNC (Use ITC subjects)

**Comment by kahinimehta** [comment]
Cifti with cortical for application section

**Comment by kahinimehta** [comment]
Results: 

mean + std matrix of cortical thickness and matrices in some atlas

So 4 by 2 figure

**Comment by kahinimehta** [comment]
QA:

Mean unscrubbed FD + number of time left - 3 histograms
Corr coif with template - 3 by 3  —> desc_linc_qc.csv

**Comment by kahinimehta** [comment]
Main figure: all the data we can get 
HCP: Not concatenated - run 1
ABCD: Concatenated
PNC: Not concatenated

**Comment by kahinimehta** [comment]
- [ ] Edits by co-authors
- [ ] Add financial info and disclosures before submitting

**Comment by kahinimehta** [comment]
- [ ] Add NMIND checklist 
- [ ] Add new atlas as requested by Damien: Hermasillo
- [ ] Comments from Chris

**Comment by tsalo** [comment]
Since the manuscript has been accepted, I think we can close this.
