### ISSUE TITLE
Issue with --warp-surfaces-native2std

### ISSUE THREAD

**Issue by Bramdiamond** [PennLINC/xcp_d#722]
## Summary
I'm receiving a crashfile on the following node: `xcpd_wf.single_subject_SA119_wf.cifti_postprocess_0_wf.execsummary_wf.get_std2native_transform`

I'm running the following command through singularity container:
```
singularity run \
	--cleanenv -B /projects,$FS_LICENSE:/opt/freesurfer/license.txt \
	/projects/p30952/environment/singularity_images/${XCP_d_VER}.simg \
	--verbose \
	--participant_label ${subject} \
	--input-type fmriprep \
	--nthreads 12 \
	--mem_gb 24 \
	--smoothing 3 \
	--despike \
	--nuisance-regressors acompcor_gsr \
	-d 11.2 \
	--bpf-order 2 \
        --motion-filter-type notch \
        --band-stop-min 10 \
        --band-stop-max 30 \
        --lower-bpf 0.01 \
	--upper-bpf 0.1 \
	--fd-thresh 0.4 \
        --dcan-qc \
        --cifti \
        --warp-surfaces-native2std \
	--work_dir ~/projects/b1145/bram/work \
	${BIDS_DIR}/derivatives/fmriprep-22.1.0 \
	${BIDS_DIR}/derivatives/${XCP_d_VER} \
        participant
```

## Additional details
- Here is a zip file containing the slrum output, crash report, and final html: 
[warp-surface-native2std_crash.zip](https://github.com/PennLINC/xcp_d/files/10238541/warp-surface-native2std_crash.zip)
- xcp_d version: 0.3.0+0.g5a726e9.dirty
- fmriprep run with the following command:
```
singularity run \
        --cleanenv -B /projects \
        /projects/p30952/environment/singularity_images/${FMRIPREP_VER}.simg \
        ${BIDS_DIR} \
        ${FMRIPREP_DIR} \
        participant --participant-label ${subject} \
        -w ${WORK_DIR} \
        --omp-nthreads 8 \
        --nthreads 12 \
        --mem_mb 24000 \
        --fs-license-file ${FS_LICENSE} \
	--fs-subjects-dir ${FMRIPREP_DIR}/sourcedata/freesurfer \
        --output-spaces MNI152NLin2009cAsym fsLR fsaverage \
        --cifti-output 91k \
        --fd-spike-threshold 0.4 \
        --dvars-spike-threshold 1.5 \
	--use-syn-sdc warn \
	--dummy-scans 4
```

**Comment by tsalo** [comment]
I think this might be the same problem as #684. I'm hoping that it is resolved in the current unstable version, but I also noticed that the version you used is >0.3.0. Do you know if your version is from after #695 was merged?

**Comment by Bramdiamond** [comment]
I built the container on 12/07; so I believe it was after the merge.

**Comment by tsalo** [comment]
Darn! The good news is that I think #721 actually does fix this problem. The bad news is that I don't know how the bug was happening. With your fMRIPrep call, I wouldn't think there would be space-MNI152NLin6Asym_res-2 NIFTI files, like the one that xcp_d tried to use. Even so, with the cifti flag, the executive summary workflow should select the NIFTI file based on the template-to-T1w transform, which is the file that doesn't match...

Regardless, I will try to get #721 ready to merge ASAP.

**Comment by Bramdiamond** [comment]
I first ran the fMRIPrep command with MNI152NLin6Asym output space, so those files do exist. @smeisler recommended that I run with MNI152NLin2009cAsym, so I reran the fMRIPrep command. It must have updated the directory without removing the space-MNI152NLin6Asym_res-2 NIFTI files.

**Comment by tsalo** [comment]
I've merged #721. If you're able, would you mind trying out the newest unstable version on your data?

**Comment by tsalo** [comment]
@bramdiamond, do you know if this bug is still around?

**Comment by tsalo** [comment]
@Bramdiamond I'm going to close this issue for now, but please reopen it if you come across this bug again.
