### ISSUE TITLE
Replace DerivativesDataSink once niworkflows 1.7.1 is released

### ISSUE THREAD

**Issue by tsalo** [PennLINC/xcp_d#739]
## Summary

Now that https://github.com/nipreps/niworkflows/pull/762 has been merged, we can import `DerivativesDataSink` instead of using the (pre-relicensing) source code ourselves.

## Additional details

Less code we have to manage.

## Next steps

1. Wait for 1.7.1 release.
2. Replace DerivativesDataSink code with import. Inherit the niworkflows version in a new class, injecting our config file.

**Comment by effigies** [comment]
Niworkflows 1.7.1 was just released.

**Comment by tsalo** [comment]
🎉 Thanks so much!!

**Comment by tsalo** [comment]
I should have closed this with #647. Closing now.
