### ISSUE TITLE
Zero-out parcels with <50% coverage

### ISSUE THREAD

**Issue by tsalo** [PennLINC/xcp_d#756]
## Summary
For CIFTIs, replace non-zero/non-NaN time series with ones, then run the parcellation to get the percent coverage of each parcel. We can then threshold this and use it as a mask to replace time series from parcels with poor coverage with all zeros.

Stems from https://github.com/PennLINC/xcp_d/issues/700#issuecomment-1387372219.

**Comment by mattcieslak** [comment]
Meet with DCAN
Maybe write out a text file that has parcelwise coverage
