### ISSUE TITLE
"Desc" entity not recognized when pointing to wrong folder

### ISSUE THREAD

**Issue by kahinimehta** [PennLINC/xcp_d#804]
## Summary
When you supply XCP with the 'derivatives' directory as input, rather than 'derivatives/fmriprep', it returns a misleading error: 
`ValueError:'desc' is not a recognized entity. If you're sure you want to impose this constraint, set invalid_filters='allow'.`
## Additional details

- xcp_d version: 0.3.2

**Comment by tsalo** [comment]
I'm not sure how best to solve this. Perhaps we could look for a specific file in the derivatives folder (e.g., dataset_deescription.json)?

**Comment by kahinimehta** [comment]
That might be a good idea
