### ISSUE TITLE
[DCAN] Add "none" option for nuisance regression strategy

### ISSUE THREAD

**Issue by tsalo** [PennLINC/xcp_d#845]
## Summary

Users have requested the ability to run XCP-D without denoising (e.g., #775). Adding a nuisance regression strategy that doesn't perform nuisance regression could serve this purpose.

+1 from Ted.

**Comment by smeisler** [comment]
Would `none` still include linear trend and intercept?

**Comment by moser297** [comment]
I agree with @tsalo. I think 'none' should do none of these
