### ISSUE TITLE
Using custom-confounds combined with --nuisance-regressors custom fails

### ISSUE THREAD

**Issue by mfschmidt** [PennLINC/xcp_d#846]
## Summary
We first use fMRIPrep 23.0.1 to pre-process our data, then would like to use a smaller set of confounds for generating connectivity than is available in xcp_d's set of named strategies. To accomplish this, we ask xcp_d not to generate its own confounds with `--nuisance-regressors custom` and add our own confounds with `--custom_confounds /path_to_confounds`. In the docker context, this fails to 'consolidate_confounds'.

## Additional details
I am running the following software on Ubuntu 20.04.6 LTS:
docker 23.0.1, build a5ee5b1
xcp_d version "pennlinc/xcp_d:latest", which currently matches 0.4.0rc2

### What were you trying to do?
I am trying to generate functional connectivity, ReHo, and fAlff results with xcp_d, using the following command (paths are obviously specific to my own machine). The data I'm processing contain a T1w image and two task-rest fMRI scans with pepolar fieldmaps.

```bash
docker run --rm -it \
-v /var/data/fampath_upmc/derivatives/fmriprep_23.0.1:/fmriprep:ro \
-v /var/data/fampath_upmc/derivatives/custom_confounds_23.0.1:/custom_confounds:ro \
-v /tmp/work:/work:rw -v /var/data/fampath_upmc/derivatives/xcpd_040rc2_c:/out:rw \
pennlinc/xcp_d:latest /fmriprep /out participant \
--participant-label P10023 \
-w /work --clean-workdir --input-type fmriprep --smoothing 5 \
--nuisance-regressors custom --custom_confounds /custom_confounds \
--fd-thresh 0 --dummy-scans auto
```

### What did you expect to happen?
I expect complete results and an html report describing them.

### What actually happened?
The `xcpd_wf.single_subject_P10023_wf.nifti_postprocess_0_wf.prepare_confounds_wf.consolidate_confounds` function raises an exception. That exception does not cause the entire pipeline to fail, but prevents results from being generated. So the pipeline continues on and reports 2 errors (same for each of two resting state scans) at its conclusion.

```
230406-16:06:58,640 nipype.workflow WARNING:
	 [Node] Error on "xcpd_wf.single_subject_P10023_wf.nifti_postprocess_0_wf.prepare_confounds_wf.consolidate_confounds" (/work/xcpd_wf/single_subject_P10023_wf/nifti_postprocess_0_wf/prepare_confounds_wf/consolidate_confounds)
230406-16:07:00,557 nipype.workflow ERROR:
	 Node consolidate_confounds failed to run on host 4e444f55e38e.
230406-16:07:00,566 nipype.workflow ERROR:
	 Saving crash info to /out/xcp_d/sub-P10023/log/crash-20230406-160700-root-consolidate_confounds-bc1d0f68-6359-4174-8cb3-8b15321aa138.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node consolidate_confounds.

Traceback:
	Traceback (most recent call last):
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 398, in run
	    runtime = self._run_interface(runtime)
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/utility/wrappers.py", line 142, in _run_interface
	    out = function_handle(**args)
	  File "<string>", line 29, in consolidate_confounds
	  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/utils/confounds.py", line 421, in load_confound_matrix
	    confounds_df = pd.read_table(custom_confounds, sep="\t")
	  File "/usr/local/miniconda/lib/python3.8/site-packages/pandas/io/parsers.py", line 689, in read_table
	    return _read(filepath_or_buffer, kwds)
	  File "/usr/local/miniconda/lib/python3.8/site-packages/pandas/io/parsers.py", line 462, in _read
	    parser = TextFileReader(filepath_or_buffer, **kwds)
	  File "/usr/local/miniconda/lib/python3.8/site-packages/pandas/io/parsers.py", line 819, in __init__
	    self._engine = self._make_engine(self.engine)
	  File "/usr/local/miniconda/lib/python3.8/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
	    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
	  File "/usr/local/miniconda/lib/python3.8/site-packages/pandas/io/parsers.py", line 1867, in __init__
	    self._open_handles(src, kwds)
	  File "/usr/local/miniconda/lib/python3.8/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
	    self.handles = get_handle(
	  File "/usr/local/miniconda/lib/python3.8/site-packages/pandas/io/common.py", line 558, in get_handle
	    ioargs = _get_filepath_or_buffer(
	  File "/usr/local/miniconda/lib/python3.8/site-packages/pandas/io/common.py", line 371, in _get_filepath_or_buffer
	    raise ValueError(msg)
	ValueError: Invalid file path or buffer object type: <class 'NoneType'>
```

At the end of this process, I see two error logs at `.../xcp_d/sub-P10023/log/`, each with this at line 6:
```custom_confounds_file = <undefined>```

## Reproducing the bug
I don't know if it's possible to reproduce this without my configuration and data, but I tried the following steps to track down the source of the problem. I hope my investment of time helps to save someone else's, and I'm happy to continue debugging if there are other ideas.

1. It seemed like maybe xcp_d could not find my custom confound file, so after triple-checking all docker mounts and paths, I tried intentionally giving it a bad path to the file. With a bad path, I get `ValueError: Custom confounds location does not exist: /custom_confoundssss` and xcp_d stops. I tried naming the files poorly, resulting in `FileNotFoundError: Custom confounds file not found: /custom_confounds/sub-P10023_ses-10023_task-rest_run-01_desc-confounds_timeseries.tsv` and a stopped xcp_d. I also got a bash shell inside the xcp_d docker container while it was running with correct paths and was able to cat the confound files in /custom_confounds/. So I am confident the volumes are mapped correctly and files are available in the container.

2. I wanted to see what the `load_confound_matrix` function was receiving as input, since that's the function raising the exception. I cloned the repository and worked through ensuring xcp_d could run locally without docker. I launched xcp_d in my PyCharm debugger, but could not get xcp_d to stop at `load_confound_matrix` with a breakpoint. I assume that's due to multiprocessing spawning a new process without my debugger attached, but that's conjecture that may not be true. Interestingly, running locally in PyCharm's debugger resulted in a complete and successful run of xcp_d without exceptions. My local arguments are not identical, but are equivalent to the docker arguments, except for differences in docker volume mappings.

```
/home/mike/mnt/lorenzhome/Projects/xcp_d/xcp_d/__main__.py \
/home/mike/mnt/lorenzdata/fampath_upmc/derivatives/fmriprep_23.0.1 \
/home/mike/mnt/lorenzdata/fampath_upmc/derivatives/xcpd_040rc2_local \
participant --participant-label P10023 \
-w /var/tmp --input-type fmriprep --smoothing 5 \
--nuisance-regressors custom \
--custom_confounds /home/mike/mnt/lorenzdata/fampath_upmc/derivatives/custom_confounds_23.0.1 \
--fd-thresh 0 --dummy-scans auto
```

When this completes, there are no error files in logs, but I can look in `/var/tmp/xcpd_wf/single_subject_P10023_wf/nifti_postprocess_0_wf/prepare_confounds_wf/consolidate_confounds/_report/` and the report.rst file has this at line 6 (for comparison to the failed error log above):

```* custom_confounds_file : /home/mike/mnt/lorenzdata/fampath_upmc/derivatives/custom_confounds_23.0.1/sub-P10023_ses-10023_task-rest_run-01_desc-confounds_timeseries.tsv
```

There is also a confounds.tsv file in `/var/tmp/xcpd_wf/single_subject_P10023_wf/nifti_postprocess_0_wf/prepare_confounds_wf/consolidate_confounds/` from this successful run. The analogous work directory from failed docker runs contains a few pklz files, but no confounds.tsv.

## Conclusions

I apologize for the amount of detail here, but I think it demonstrates the issue fairly well and implicates one specific function as the problem. I just can't figure out whether something in that function is causing the problem or if it's a victim of receiving bad data from elsewhere. I also don't even have a hypothesis about why it would work differently in docker vs running on the host.

Thank you for xcp_d, and your time in supporting it. It's truly appreciated.

**Comment by mfschmidt** [comment]
@tsalo It looks like you fixed this two weeks ago in https://github.com/PennLINC/xcp_d/pull/835/commits/d2c78e0510f06fbf20270c077ada89e0d992ce08. This was after the 0.4.0rc2 tag I was using for docker, and before the git clone I used for the successful version in the debugger. When I built my own local docker image with current code, it also worked correctly.

So I guess you can close this as already fixed.

Thanks again for your many contributions to neuroimaging software!! :)

**Comment by tsalo** [comment]
I'm glad that the bug was resolved. Thank you for the detailed bug report, in any case!
