### ISSUE TITLE
Using acompcor as nuisance parameters did not result in c_comp_cor_ and w_comp_cor_ as regressors in design matrix

### ISSUE THREAD

**Issue by narunpat** [PennLINC/xcp_d#849]
## Summary
Using acompcor  as  nuisance parameters did not result in c_comp_cor_ and w_comp_cor_ as regressors in design matrix

## Additional details
- xcp_d version: 0.3.2 and 0.4.0rc2
- fmriprep version: 23.0.0
- Docker version: 20.10.21, build 20.10.21-0ubuntu1~22.04.2
- Singularity version: singularity-ce version 3.11.0

### What were you trying to do?
We tried to use acompcor as nuisance parameters and hrf-convolved task events as custom confounds.

### What did you expect to happen?
We expect to have the design matrix with five of c_comp_cor_ and five of w_comp_cor along with hrf-convolved task events among others.

### What actually happened?
With 0.3.2, in the design matrix, we got hrf-convolved task events, cosine, rot_ and trans_ and their derivatives.

With 0.4.0rc2, in the design matrix, we got cosine, rot_ and trans_ and their derivatives. We did not have hrf-convolved task events.

## Reproducing the bug
We tried to compute functional connectivity during a working-memory task in the Human Connectome Project- Young Adults. We converted HCP to BIDS following this tutorial https://micapipe.readthedocs.io/en/latest/pages/04.start2end/index.html. We then ran fmriprep 23.0.0 as follows. 

```
singularity run --cleanenv ${image_path} \
${bids_path}  \
${out_path} \
participant --participant_label ${participant_id} \
--write-graph \
--notrack \
--nthreads 12 \
--omp-nthreads 11 \
--mem_mb 100000 \
--skip_bids_validation \
--fs-license-file ${license_path} \
--work-dir ${work_dir_path} \
--cifti-output \
--ignore slicetiming \
--fs-subjects-dir ${fs_sub_dir} \
--use-aroma
```

We got the attached confound file. 
[sub-100206_task-WM_dir-LR_desc-confounds_timeseries.txt](https://github.com/PennLINC/xcp_d/files/11216284/sub-100206_task-WM_dir-LR_desc-confounds_timeseries.txt)
(note the file is actually a tsv, but github doesn't allow us to upload a tsv file here, so I converted it to a txt).

We then run xcp_d 0.3.2 with acompcor and custom confounds for hrf-convolved task events (attached).
[sub-100206_task-WM_dir-LR_desc-confounds_timeseries.txt](https://github.com/PennLINC/xcp_d/files/11216280/sub-100206_task-WM_dir-LR_desc-confounds_timeseries.txt)
(again, it's actually a tsv).

```
docker run --rm -it -v /media/hcs-sci-psy-narun/HCP-YA-MICA-BIDS/derivatives/fmriprep:/fmriprep:ro -v /media/hcs-sci-psy-narun/HCP-YA-MICA-BIDS/derivatives/custom_confounds:/custom_confounds:ro -v /tmp/wkdir:/work:rw -v /media/hcs-sci-psy-narun/HCP-YA-MICA-BIDS/derivatives/xcp_dO:/out:rw pennlinc/xcp_d:0.3.2 /fmriprep /out participant --participant-label 100206 --input-type fmriprep --cifti --smoothing 2 --task-id WM --despike --nuisance-regressors acompcor --custom_confounds /custom_confounds --dummy-scans auto --fd-thresh 0.5 --disable-bandpass-filter -w /work --dcan-qc --notrack
```

Here are the headers of the design matrix. Note there are no acompcor regressors.

```
0bk_body	0bk_faces	0bk_places	0bk_tools	2bk_body	2bk_faces	2bk_places	2bk_tools	cosine00	cosine01	cosine02	rot_x	rot_x_derivative1	rot_y	rot_y_derivative1	rot_z	rot_z_derivative1	trans_x	trans_x_derivative1	trans_y	trans_y_derivative1	trans_z	trans_z_derivative1
```
Here is the code as shown in the html output file. Note here we saw acompcor as nuisance-regressors.

```
xcp_d: /usr/local/miniconda/bin/xcp_d /fmriprep /out participant --participant-label 100206 --input-type fmriprep --cifti --smoothing 2 --task-id WM --despike --nuisance-regressors acompcor --custom_confounds /custom_confounds --dummy-scans auto --fd-thresh 0.5 --disable-bandpass-filter -w /work --dcan-qc --notrack
```
The boilerplate also says that we used aCompCor

“The top 5 aCompCor principal components from the WM and CSF compartments were selected as nuisance regressors (Behzadi et al. 2007), along with the six motion parameters and their temporal derivatives (Ciric et al. 2017; Satterthwaite et al. 2013). Additionally, custom confounds were also included as nuisance regressors.”

We then tried acompcor without any custom confounds

```
docker run --rm -it -v /media/hcs-sci-psy-narun/HCP-YA-MICA-BIDS/derivatives/fmriprep:/fmriprep:ro -v /media/hcs-sci-psy-narun/HCP-YA-MICA-BIDS/derivatives/custom_confounds:/custom_confounds:ro -v /tmp/wkdir:/work:rw -v /media/hcs-sci-psy-narun/HCP-YA-MICA-BIDS/derivatives/xcp_dNC:/out:rw pennlinc/xcp_d:0.3.2 /fmriprep /out participant --participant-label 100206 --input-type fmriprep --cifti --smoothing 2 --task-id WM --despike --nuisance-regressors acompcor --dummy-scans auto --fd-thresh 0.5 --disable-bandpass-filter -w /work --dcan-qc –notrack
```

The design matrix still doesn’t have acompcor.
```
cosine00	cosine01	cosine02	rot_x	rot_x_derivative1	rot_y	rot_y_derivative1	rot_z	rot_z_derivative1	trans_x	trans_x_derivative1	trans_y	trans_y_derivative1	trans_z	trans_z_derivative1
```

We then tried 36P with custom confounds.

```
docker run --rm -it -v /media/hcs-sci-psy-narun/HCP-YA-MICA-BIDS/derivatives/fmriprep:/fmriprep:ro -v /media/hcs-sci-psy-narun/HCP-YA-MICA-BIDS/derivatives/custom_confounds:/custom_confounds:ro -v /tmp/wkdir:/work:rw -v /media/hcs-sci-psy-narun/HCP-YA-MICA-BIDS/derivatives/xcp_d-36P:/out:rw pennlinc/xcp_d:0.3.2 /fmriprep /out participant --participant-label 100206 --input-type fmriprep --cifti --smoothing 2 --task-id WM --despike --nuisance-regressors 36P --custom_confounds /custom_confounds --dummy-scans auto --fd-thresh 0.5 --disable-bandpass-filter -w /work --dcan-qc –notrack
```

Here we found that 36p is added to the design matrix as expected:

```
0bk_body	0bk_faces	0bk_places	0bk_tools	2bk_body	2bk_faces	2bk_places	2bk_tools	csf	csf_derivative1	csf_derivative1_power2	csf_power2	global_signal	global_signal_derivative1	global_signal_derivative1_power2	global_signal_power2	rot_x	rot_x_derivative1	rot_x_derivative1_power2	rot_x_power2	rot_y	rot_y_derivative1	rot_y_derivative1_power2	rot_y_power2	rot_z	rot_z_derivative1	rot_z_derivative1_power2	rot_z_power2	trans_x	trans_x_derivative1	trans_x_derivative1_power2	trans_x_power2	trans_y	trans_y_derivative1	trans_y_derivative1_power2	trans_y_power2	trans_z	trans_z_derivative1	trans_z_derivative1_power2	trans_z_power2	white_matter	white_matter_derivative1	white_matter_derivative1_power2	white_matter_power2
```

Note with 0.4.0rc2, we tried acompcor and custom confounds as before

```
docker run --rm -it -v /media/hcs-sci-psy-narun/HCP-YA-MICA-BIDS/derivatives/fmriprep:/fmriprep:ro -v /media/hcs-sci-psy-narun/HCP-YA-MICA-BIDS/derivatives/custom_confounds:/custom_confounds:ro -v /tmp/wkdir:/work:rw -v /media/hcs-sci-psy-narun/HCP-YA-MICA-BIDS/derivatives/xcp_d-4:/out:rw pennlinc/xcp_d:0.4.0rc2 /fmriprep /out participant --participant-label 100206 --input-type fmriprep --cifti --smoothing 2 --task-id WM --despike --nuisance-regressors acompcor --custom_confounds /custom_confounds --dummy-scans auto --fd-thresh 0.5 --disable-bandpass-filter -w /work --dcan-qc --notrack
```
Here we lost the custom confounds as well as acompcor! 

```
cosine00	cosine01	cosine02	rot_x	rot_x_derivative1	rot_y	rot_y_derivative1	rot_z	rot_z_derivative1	trans_x	trans_x_derivative1	trans_y	trans_y_derivative1	trans_z	trans_z_derivative1	linear_trend	intercept
```
Let me know if you need additional information for you to reproduce the problems. We are more than happy to send you any files.

**Comment by tsalo** [comment]
Thanks for reporting this @narunpat. I think this must be due to a bug in nilearn's load_confounds, with loading compcor regressors in newer versions of fMRIPrep. I'll have to write some internal code to load acompcor regressors.

I believe the custom confounds issue is a bug in 0.4.0rc2 that was fixed in #835. It should be fixed in the next release.

**Comment by tsalo** [comment]
@narunpat I believe it should be fixed now. I will make another release soon, but if you try on `unstable` and it doesn't work, please reopen this issue.

**Comment by narunpat** [comment]
Thank you so much. I just would like to confirm that the issues were fixed in the `unstable`.
