### ISSUE TITLE
Couldn't find QC indexes for BOLD-T1w coregistration quality and BOLD-Template normalization quality

### ISSUE THREAD

**Issue by narunpat** [PennLINC/xcp_d#856]
## Summary
I couldn't find the following QC indexes:
1) BOLD-T1w coregistration quality - Dice similarity index, Coverage and Pearson correlation
2) BOLD-Template normalization quality - Dice similarity index, Coverage and Pearson correlation

According to the [workflow](https://xcp-d.readthedocs.io/en/latest/workflows.html), these indexes were computed.

## Additional details
- xcp_d version: 0.3.2 and 0.4.0rc2, and 0.4.0rc2+9.gca6db49
- fmriprep version: 23.0.0
- Docker version: 20.10.21, build 20.10.21-0ubuntu1~22.04.2
- Singularity version: singularity-ce version 3.11.0

### What were you trying to do?
We hope to see BOLD-T1w coregistration quality and BOLD-Template normalization quality QCs and use them to exclude participants.

### What did you expect to happen?
We expect a file that shows Dice similarity index, Coverage and Pearson correlation for coregistration and  normalization quality. This file might be created, but we may have missed it. If this is the case, perhaps improving documentation might be needed.

### What actually happened?
we found a file with a suffix `_desc-linc_qc.csv`. In this file, there are these columns:
```
sub,task,dir,space,den,meanFD,relMeansRMSMotion,relMaxRMSMotion,meanDVInit,meanDVFinal,num_censored_volumes,nVolsRemoved,motionDVCorrInit,motionDVCorrFinal
```
We couldn't find  Dice similarity index, Coverage and Pearson correlation here.

## Reproducing the bug
We provided the script for our attempt #849 using HCP-YA data. Note we also tried the unstable version (0.4.0rc2+9.gca6db49)

Thank you so much for your hard work!

**Comment by tsalo** [comment]
I think the problem is with your input data organization and/or flags. If you ran XCP-D with `--cifti`, normalization and coregistration metrics won't be calculated, as those rely on volumetric images that aren't used in the CIFTI workflow. The HCP `input-type` automatically enables `--cifti`.

**Comment by narunpat** [comment]
Aha, that makes sense. Thank you so much tsalo.
