### ISSUE TITLE
the BrainSprite generated images in Executive Summary from the 'unstable' 

### ISSUE THREAD

**Issue by narunpat** [PennLINC/xcp_d#858]
## Summary
I was unsure if this was the right place to provide feedback on the `unstable`. We found that the BrainSprite-generated images in Executive Summary created by the 'unstable' xcp_d weren't loaded correctly. 

## Additional details
xcp_d version: 0.4.0rc2 and 0.4.0rc2+9.gca6db49 (i.e., 'unstable')
fmriprep version: 23.0.0
Docker version: 20.10.21, build 20.10.21-0ubuntu1~22.04.2
Singularity version: singularity-ce version 3.11.0

### What were you trying to do?
We tried the `unstable` and found a problem with the BrainSprite generated images.

### What did you expect to happen?
Based on the Executive Summary from 0.4.0rc2, we expect to see well-aligned contours and  brain anatomical images, generated by BrainSprite.

### What actually happened?
 We found that the BrainSprite generated images in Executive Summary under 'unstable'  wasn't loaded correctly. See our implementation of xcp_d #849.

From 0.4.0rc2
![Screen Shot 2023-04-15 at 10 37 51 AM](https://user-images.githubusercontent.com/38054414/232166313-eadfacba-d018-4ea6-8c31-38c7ee70db3d.png)

From `unstable`
![Screen Shot 2023-04-15 at 10 38 01 AM](https://user-images.githubusercontent.com/38054414/232166359-06862dad-4897-4d71-984f-fca3fc6ac372.png)

Note the other images look fine on both versions. For example,
![Screen Shot 2023-04-15 at 10 47 59 AM](https://user-images.githubusercontent.com/38054414/232167383-f2ba97ad-e84b-4709-8b23-180238c5eac4.png)

**Comment by tsalo** [comment]
That's definitely a bug. Can you provide your command-line call? Also, if you still have the log, can you share the list of loaded surface files that XCP-D should print out? I need to know what combination of native, fsnative, fsLR, and MNI152NLin6Asym anatomical and surface files led to the problem, and the "collected files" portions of the log should tell me that.

**Comment by narunpat** [comment]
thank you so much for your reply @tsalo. 

here is the command-line call we used 
```
docker run --rm -it -v /media/hcs-sci-psy-narun/HCP-YA-MICA-BIDS/derivatives/fmriprep:/fmriprep:ro -v /media/hcs-sci-psy-narun/HCP-YA-MICA-BIDS/derivatives/custom_confounds:/custom_confounds:ro -v /tmp/wkdir:/work:rw -v /media/hcs-sci-psy-narun/HCP-YA-MICA-BIDS/derivatives/xcp_d-U2-4tsalo:/out:rw pennlinc/xcp_d:unstable /fmriprep /out participant --participant-label 100206 --input-type fmriprep --smoothing 2 --cifti --task-id WM --despike --nuisance-regressors acompcor --custom_confounds /custom_confounds --dummy-scans auto --fd-thresh 0 --upper-bpf 0.1 -w /work --dcan-qc --notrack
```
I attached a full log here
[log.txt](https://github.com/PennLINC/xcp_d/files/11241315/log.txt)

Thank you again. Sorry for posting so many issues lately. We appreciate your prompt replies to remedy them.
