### ISSUE TITLE
Allow XCP-d to process more than one task

### ISSUE THREAD

**Issue by williamvdv** [PennLINC/xcp_d#873]
## Summary

I would like to run analysis for more than one task ID. Already there is the capacity to do one task with the --task-id  flag or all of them if the flag is not specified. I might not have tried everything so perhaps XCP_d already does this, and if so it would be nice to see it in the documentation. Currently I can do one of them at a time, in separate jobs.

## Additional details

I have a data set in which I am applying custom confounds to some tasks that I am interested in. I have generated custom confounds for those tasks but not for all.

If I run it in docker (xcp_d version 0.4.0rc2+16.g6109c09) without the --task-id  flag XCP_d errors with:

  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/utils/confounds.py", line 108, in get_custom_confounds
    raise FileNotFoundError(f"Custom confounds file not found: {custom_confounds_file}")
FileNotFoundError: Custom confounds file not found: /custom_confounds/sub-993675_task-rest_dir-LR_run-1_desc-confounds_timeseries.tsv

because I have not created custom confounds for the resting state.

If I run it with --task-id "WM, LANGUAGE" for instance I get:

FileNotFoundError: No BOLD data found in allowed spaces (fsLR).

because there is no task "WM, LANGUAGE", I have also tried feeding XCP_d them in a list.

I can run the tasks consecutively as separate jobs and it knits subsequent jobs to the XCP-d derivative, which is very nice. I am curious to know if running the tasks as separate jobs results in increased overhead. It would be efficient if I could apply all the task confounds as one job.

## Next steps

I notice the flag already accepts a string. If the string has n values separated by a comma they could be taken and split into n separated tasks. I guess you have a list that contains all the tasks when you run it without the flag, or if there are two tasks with one label. It defaults to all if a task is not specified, so perhaps all the tasks are stored somewhere in that instance and iterated through.

An example flag could be

--task-id "WM, LANGUAGE"

Thanks for all your hard work and dedication in creating such an amazing container!

**Comment by tsalo** [comment]
`--task-id` only accepts a single task, but running XCP-D without that parameter will run all of the tasks for the subject. If you want to run a specific subset of tasks, you can use the BIDS filter file (`--bids-filter-file`). You're totally right that the documentation should be expanded to showcase that parameter.
