### ISSUE TITLE
[DCAN] Add option to retain certain amount of time

### ISSUE THREAD

**Issue by tsalo** [PennLINC/xcp_d#883]
## Summary

The DCAN team wants an option to retain a specific amount of time in the outputs (e.g., time series and correlation matrices), as done in [Feczko et al. (2021)](https://www.biorxiv.org/content/10.1101/2021.07.09.451638v1).

The parameter can be called `--exact-time`, and it will be mutually exclusive with `--min-time`.

## Open questions

- Do we want to output both the exact-time time series/matrices and the regular censored ones, or just the exact-time ones if `--exact-time` is used?
- If the DCAN team wants to use `--exact-time`, do we need to write out the interpolated time series?
- Is the variance associated with subsampling important? Should we calculate the correlation matrices for a number of permutations?

## Additional details

1. If the amount of good quality data is less than `--exact-time`, then the run won't be postprocessed at all, as with `--min-time`.
2. The random set of censored volumes will be stored in the temporal mask file, in a new column called `random_censor`.
3. The censored volumes will be plotted in the design matrix and censoring plots. In the censoring plot, it'll have a different color than the high-motion outliers.

**Comment by tsalo** [comment]
Thank you for your answers. 

>--exact-time should only affect the output correlation matrices, not the time-series outputs. It should produce additional correlation matrices as specified by --exact-time

When you say "additional correlation matrices", does that mean there should be both correlation matrices for the full time series and correlation matrices for the exact-time time series?

One more question- do you want XCP-D to allow multiple `--exact-time` values? Or just one?

**Comment by ericfeczko** [comment]
That would maintain the same behavior we have for our current pipelines and materials.

If you could allow for multiple values, that would be awesome -- depends on how much burden that adds :)
