### ISSUE TITLE
[DCAN] Retain additional HCP and ABCD surface derivatives

### ISSUE THREAD

**Issue by tsalo** [PennLINC/xcp_d#886]
## Summary

Here is a list of surface files from the HCP-YA and ABCD derivatives. Which ones should we add to the XCP-D derivatives?

These files are located in the `MNINonLinear/fsaverage_LR32k` folder.

| Filename | Included? | Notes |
| - | - | - |
| *.aparc.32k_fs_LR.label.gii | | |
| *.aparc.a2009s.32k_fs_LR.label.gii | | |
| *.ArealDistortion_FS.32k_fs_LR.shape.gii | | |
| *.ArealDistortion_MSMSulc.32k_fs_LR.shape.gii | | |
| *.atlasroi.32k_fs_LR.shape.gii | | |
| *.BA.32k_fs_LR.label.gii | | HCP-YA only |
| *.corrThickness.32k_fs_LR.shape.gii | | This is curvature-corrected thickness, which I didn't realize. |
| *.curvature.32k_fs_LR.shape.gii | In progress (#887) | |
| *.flat.32k_fs_LR.surf.gii | | |
| *.inflated.32k_fs_LR.surf.gii | ✅ | Made from pial/wm in XCP-D |
| *.inflated_MSMAll.32k_fs_LR.surf.gii | | HCP-YA only |
| *.midthickness.32k_fs_LR.surf.gii | ✅ | Made from pial/wm in XCP-D |
| *.midthickness_MSMAll.32k_fs_LR.surf.gii | | HCP-YA only |
| *.MyelinMap.32k_fs_LR.func.gii | | |
| *.MyelinMap_BC.32k_fs_LR.func.gii | | |
| *.pial.32k_fs_LR.surf.gii | ✅ | |
| *.pial_MSMAll.32k_fs_LR.surf.gii | | HCP-YA only |
| *.RefMyelinMap.32k_fs_LR.func.gii | | |
| *.refsulc.32k_fs_LR.shape.gii | | |
| *.SmoothedMyelinMap.32k_fs_LR.func.gii | | |
| *.SmoothedMyelinMap_BC.32k_fs_LR.func.gii | | |
| *.sphere.32k_fs_LR.surf.gii | | |
| *.sulc.32k_fs_LR.shape.gii | In progress (#887) | |
| *.thickness.32k_fs_LR.shape.gii | In progress (#887) | Uncorrected cortical thickness. |
| *.very_inflated.32k_fs_LR.surf.gii | ✅ | Made from pial/wm in XCP-D |
| *.very_inflated_MSMAll.32k_fs_LR.surf.gii | | HCP-YA only |
| *.white.32k_fs_LR.surf.gii | ✅ | |
| *.white_MSMAll.32k_fs_LR.surf.gii | | HCP-YA only |
| *.EdgeDistortion_FS.32k_fs_LR.shape.gii | | ABCD only |
| *.EdgeDistortion_MSMSulc.32k_fs_LR.shape.gii | | ABCD only |
| *.StrainJ_FS.32k_fs_LR.shape.gii | | ABCD only |
| *.StrainJ_MSMSulc.32k_fs_LR.shape.gii | | ABCD only |
| *.StrainR_FS.32k_fs_LR.shape.gii | | ABCD only |
| *.StrainR_MSMSulc.32k_fs_LR.shape.gii | | ABCD only |

## Open questions

1. Which files do you want written out to the XCP-D derivatives?
2. What is the content of each file?
3. What output description entity and suffix do you want for each output file?
4. Do you plan to add any of these to sMRIPrep?

## Additional details

All of these outputs are already in fsLR space, so they should just need to be copied to the output directory without performing any additional processing.

I also don't think fMRIPrep produces a number of these, so they may only be processed for HCP and ABCD derivatives.

**Comment by madisoth** [comment]
I'd prioritize adding the myelin map-related files from the ABCD derivatives.  From the table I'm pretty sure the HCP-YA data weren't processed with any version of the ABCD-BIDS pipeline, AFAIK it doesn't run MSMAll (but does run MSMSulc). 


These are template files and don't need to be included: 
*.atlasroi.32k_fs_LR.shape.gii 		
*.RefMyelinMap.32k_fs_LR.func.gii 		
*.refsulc.32k_fs_LR.shape.gii

Also I'd use desc-corrected or something similar to differentiate *.corrThickness.32k_fs_LR.shape.gii from sMRIPrep's thickness derivatives, which aren't curvature-corrected (*thickness.32k_fs_LR.shape.gii is also non-corrected)

**Comment by tsalo** [comment]
Thanks @madisoth. The HCP-YA data came from the HCP1200 dataset, so I imagine they were processed with the HCP pipeline.

Do you have any recommendations for naming the myelin map outputs? It looks like there are four: `MyelinMap.32k_fs_LR.func.gii`, `MyelinMap_BC.32k_fs_LR.func.gii`, `SmoothedMyelinMap.32k_fs_LR.func.gii`, and `SmoothedMyelinMap_BC.32k_fs_LR.func.gii`.

I want to make sure I have a full list of files to retain before I work on this issue. Are there any others your team wants passed along to the XCP-D derivatives?

**Comment by madisoth** [comment]
In Collection 3165 (ABCC) it looks like we named them:

```
_myelinmap.dscalar.nii
_desc-smoothed_myelinmap.dscalar.nii
```

We didn't include the bias-corrected ("BC") maps-- not sure if there was a particular reason why-- but if including them in xcp_d, I'd go with

```
_desc-biasCorrected_myelinmap.dscalar.nii
_desc-biasCorrectedSmoothed_myelinmap.dscalar.nii
```

Also if there's an alternative that would better clarify that the "smoothed" maps here are smoothed by the HCP / DCAN pipeline, and not by xcp_d's `--smoothing`, I'd be open to that too though

Besides the myelin maps, xcp_d already covers all the 32k derivatives we provide in C3165, so that's it for to retain as far as I know.

**Comment by tsalo** [comment]
Is the myelin map quantitative? Meaning does it have meaningful units?

**Comment by madisoth** [comment]
The units of the myelin maps are arbitrary, it's derived from the T1w/T2w intensity ratio

**Comment by tsalo** [comment]
In that case I'll call them `_myelinw`, rather than `_myelinmap`. Suffixes ending with `map` are reserved for quantitative images.
