### ISSUE TITLE
Bugs in utils.bids.collect_morphometry_data when using HCP dataset.

### ISSUE THREAD

**Issue by trichtu** [PennLINC/xcp_d#923]
## Summary
The errors is reported that the work connect could not find the lh.cortical_thickness_corr and rh.cortical_thickness_corr in the HCP dataset.

## Additional details

- xcp_d version: 0.4

### What were you trying to do?

I am trying to preprocessing the fMRI data after HCP minimal preprocessing.

### What actually happened?

There is bugs in convert file from HCP style into fMRIprep style.

## Reproducing the bug

Enclose them in triple back-ticks (```)
Like this:
The bugs is that in the scripts in the function utils.bids.collect_morphometry_data 
The original code is
```
queries = {
        "sulcal_depth": {
            "desc": None,
            "suffix": "sulc",
        },
        "sulcal_curv": {
            "desc": None,
            "suffix": "curv",
        },
        "cortical_thickness": {
            "desc": None,
            "suffix": "thickness",
        },
        "cortical_thickness_corr": {
            "desc": "corrected",
            "suffix": "thickness",
        },
        "myelin": {
            "desc": None,
            "suffix": "myelinw",
        },
        "myelin_smoothed": {
            "desc": "smoothed",
            "suffix": "myelinw",
        },
    }
```

This leading to the bugs that it could not find the correspinding file for cortical_thickness_corr, myelin, myelin_smoothed. So I change the quary with below:

```
    queries = {
        "sulcal_depth": {
            "desc": None,
            "suffix": "sulc",
            "extension": ".shape.gii",
        },
        "sulcal_curv": {
            "desc": None,
            "suffix": "curv",
            "extension": ".shape.gii",
        },
        "cortical_thickness": {
            "desc": None,
            "suffix": "thickness",
            "extension": ".shape.gii",
        },
        "myelin": {
            "desc": None,
            "suffix": "MyelinMap",
            "extension": ".func.gii",
        },
        "myelin_smoothed": {
            "desc": "smoothed",
            "suffix": "MyelinMap",
            "extension": ".func.gii",
        },
    }

```

**Comment by tsalo** [comment]
@trichtu thank you for opening this issue. Would you mind sharing the traceback as well?
