### ISSUE TITLE
Nuissance regressors parameter: incorrect documentation for "none" option

### ISSUE THREAD

**Issue by holsmon** [PennLINC/xcp_d#935]
## Summary
The "none" option for the nuisance regressors (-p, --nuisance_regressors) is not working. Based on the xcp_documentation, the option "none" should be allowed for the --nuisance regressors parameter, but it is not. 

## Additional details

- xcp_d version: 0.4.1rc2
- Singularity version: 1.1.6-1.el7

### What were you trying to do?
I am trying to run xcp_d's pipeline using no nuisance regressors. 

### What did you expect to happen?
I expected xcp_d to run and output correlation matrices without using any nuisance regressors. I was hoping to compare the 36p output compared to using no nuisance regressors. 

### What actually happened?
xcp_d output the following error:

xcp_d: error: argument -p/--nuisance-regressors/--nuisance_regressors: invalid choice: 'none' (choose from '27P', '36P', '24P', 'acompcor', 'aroma', 'acompcor_gsr', 'aroma_gsr', 'custom')

**Comment by tsalo** [comment]
The "none" option is actually added in 0.5.0rc1. You should be able to install that version (or better yet, 0.5.0rc2) if you want to try it out. I'm hoping to properly release 0.5.0 soon, but I'm waiting on some analyses to before I do that.

If you stick with 0.4.1rc1, you may want to look at the `04.0` (unfortunate typo) version of the docs.

**Comment by holsmon** [comment]
Thank you so much! I was able to install 0.5.0rc2 and was able to get it running with the "none" option. Thank you so much for the quick reply and help.
