### ISSUE TITLE
Add xcp_d to the bids app website?

### ISSUE THREAD

**Issue by Remi-Gau** [PennLINC/xcp_d#946]
Do you want me to add xcp_d the listing of bids-app?

https://bids-apps.neuroimaging.io/apps/

Given that there are already a few "2nd order" bids-app there, it would make sense to add it.

**Comment by tsalo** [comment]
That would be amazing, thanks @Remi-Gau!

**Comment by Remi-Gau** [comment]
Feel free to merge https://github.com/bids-apps/bids-apps.github.io/pull/112

if you are good with it

make sure you are content with the short description of the bids app

**Comment by Remi-Gau** [comment]
Done
