### ISSUE TITLE
Errors in ReHo files

### ISSUE THREAD

**Issue by danella** [PennLINC/xcp_d#948]
## Summary
xcp_d is running without error. However, I am receiving the following error when I attempt to open a few of these .nii files in fsl (and a similar error when extracting data in nilearn). Here is the fsl error:

![image](https://github.com/PennLINC/xcp_d/assets/25728527/86f782f9-3c2f-47e2-acd3-735e34c1d9c7)

This is only happening sporadically (approximately 5-10% of analyses) - and I can't find a pattern.

## Additional details
- xcp_d version: 0.2.0+12.g496471e.dirty
- Singularity version: 3.9.6

### What were you trying to do?
Opening ReHo files in fsl and nilearn

### What did you expect to happen?
Open without error

### What actually happened?
Error as above; nilearn error had the same text.

**Comment by tsalo** [comment]
Can you share one of the problematic ones?

**Comment by danella** [comment]
Here you go -thanks!

[sub-400_ses-03_task-inscapes_run-1_space-MNI152NLin6Asym_reho.nii.gz](https://github.com/PennLINC/xcp_d/files/12741682/sub-400_ses-03_task-inscapes_run-1_space-MNI152NLin6Asym_reho.nii.gz)

**Comment by danella** [comment]
I am able to open the denoised BOLD file without problem. Here is the associated SLURM output:

[slurm-7147626.txt](https://github.com/PennLINC/xcp_d/files/12752043/slurm-7147626.txt)

Interestingly, I reran this participant again today and this time it worked - so it is not a reproducible error, although it happened with multiple subjects/sessions, so would be helpful to understand. Thank you!

**Comment by tsalo** [comment]
I can't see anything wrong with the ReHo workflow or the log, so I think this might be a random error on AFNI's end. In that case, it's not something I can fix on XCP-D's end.
