### ISSUE TITLE
possibility of adding --bids-database-dir

### ISSUE THREAD

**Issue by andreifoldes** [PennLINC/xcp_d#954]
## Summary
I'm struggling with telling xcp_d not to bother with processing upsampled versions of my functional runs, flagged with "res-1" in their name. 

I was thinking that having  `--bids-database-dir` flag like fmriprep can provide more flexibility in designing filter rules.

## Additional details
Added flexibility in creating filter rules.

**Comment by tsalo** [comment]
I love that idea. I'm happy to handle this at some point, but would you be interested in working on this youself?

**Comment by andreifoldes** [comment]
Yes! I would love to work on that, probably have time in 1-2 weeks time!

**Comment by tsalo** [comment]
I think this will require the Config object, so I'm prioritizing #816 first.

**Comment by psychelzh** [comment]
This will also be useful to speed up large projects with pre-built bids database.
