### ISSUE TITLE
Incorrect TR - header of nifti denoised bold

### ISSUE THREAD

**Issue by pandyasneha** [PennLINC/xcp_d#967]
## Summary

I am using XCP_D v0.5.0 to denoise fmri data preprocessed with fmriprep. I noticed that TR (repetition time) within the header of xcp_d denoised bold file (nifti image) is saved incorrectly. Our TR = 2000 ms, however nifti header shows 1000 ms. In the json it is saved correctly though. Is it possible to reflect correct TR in the nifti header as well?

## Additional details

- xcp_d version: 0.5.0
- Docker version:
- Singularity version:

### What were you trying to do?
Extract TR from denoised bold to compute additional fmri derivatives. 

### What did you expect to happen?
Get correct TR that is saved in the nifti header of the fmriprep bold series or original bold series.

### What actually happened?
Got incorrect TR which is different from both preprocessed fmri bold series and xcp_d denoised bold json.

**Comment by tsalo** [comment]
This is probably the result of using nilearn masking and unmasking. There are a number of places in the package where that happens, where I'll need to patch the resulting image's header.

**Comment by tsalo** [comment]
@pandyasneha just so you know, since this is a bug it's definitely on my to-do list to fix, but because it's also very low impact it will be fairly low priority, until I have more time to dedicate to it.

**Comment by pandyasneha** [comment]
No worries and thank you for looking into it. Now that it is known, will use the json file to extract details until it is fixed.
